/*
 * SPDX-FileCopyrightText: 2023-2024 Espressif Systems (Shanghai) CO LTD
 * SPDX-License-Identifier: MIT
 * Derived from Espressif usb_device_uac 1.3.1.
 */
#pragma once

#include "uac_config.h"

#define UAC2_ENTITY_CLOCK 0x04
#define UAC2_ENTITY_SPK_INPUT_TERMINAL 0x01
#define UAC2_ENTITY_SPK_FEATURE_UNIT 0x02
#define UAC2_ENTITY_SPK_OUTPUT_TERMINAL 0x03
#define UAC2_ENTITY_MIC_INPUT_TERMINAL 0x01
#define UAC2_ENTITY_MIC_FEATURE_TERMINAL 0x02
#define UAC2_ENTITY_MIC_OUTPUT_TERMINAL 0x03

#define TUD_AUDIO_DESC_CS_AC_TOTAL_LEN ( \
    TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + \
    TUD_AUDIO_DESC_OUTPUT_TERM_LEN)

#define TUD_AUDIO_DEVICE_DESC_LEN ( \
    TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + \
    TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CS_AC_TOTAL_LEN + \
    TUD_AUDIO_DESC_STD_AS_INT_LEN + TUD_AUDIO_DESC_STD_AS_INT_LEN + \
    TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + \
    TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN)

#define TUD_AUDIO_DESCRIPTOR(_itfnum, _stridx, _epout, _epin, _epfb) \
    TUD_AUDIO_MIC_DESCRIPTOR(_itfnum, _stridx, _epin)

#define TUD_AUDIO_MIC_DESCRIPTOR(_itfnum, _stridx, _epin) \
    TUD_AUDIO_DESC_IAD(_itfnum, 2, 0x00), \
    TUD_AUDIO_DESC_STD_AC(_itfnum, 0x00, _stridx), \
    TUD_AUDIO_DESC_CS_AC(0x0200, AUDIO_FUNC_MICROPHONE, \
                         TUD_AUDIO_DESC_CS_AC_TOTAL_LEN, \
                         AUDIO_CS_AS_INTERFACE_CTRL_LATENCY_POS), \
    TUD_AUDIO_DESC_CLK_SRC(UAC2_ENTITY_CLOCK, 1, 1, \
                           UAC2_ENTITY_MIC_INPUT_TERMINAL, 0x00), \
    TUD_AUDIO_DESC_INPUT_TERM(UAC2_ENTITY_MIC_INPUT_TERMINAL, \
                              AUDIO_TERM_TYPE_IN_GENERIC_MIC, \
                              UAC2_ENTITY_MIC_OUTPUT_TERMINAL, \
                              UAC2_ENTITY_CLOCK, MIC_CHANNEL_NUM, \
                              AUDIO_CHANNEL_CONFIG_FRONT_CENTER, 0x00, \
                              (AUDIO_CTRL_R << AUDIO_IN_TERM_CTRL_CONNECTOR_POS), \
                              0x00), \
    TUD_AUDIO_DESC_OUTPUT_TERM(UAC2_ENTITY_MIC_OUTPUT_TERMINAL, \
                               AUDIO_TERM_TYPE_USB_STREAMING, 0x00, \
                               UAC2_ENTITY_MIC_INPUT_TERMINAL, \
                               UAC2_ENTITY_CLOCK, 0x0000, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT((_itfnum) + 1, 0x00, 0x00, (_stridx) + 1), \
    TUD_AUDIO_DESC_STD_AS_INT((_itfnum) + 1, 0x01, 0x01, (_stridx) + 1), \
    TUD_AUDIO_DESC_CS_AS_INT(UAC2_ENTITY_MIC_OUTPUT_TERMINAL, AUDIO_CTRL_NONE, \
                             AUDIO_FORMAT_TYPE_I, \
                             AUDIO_DATA_FORMAT_TYPE_I_PCM, MIC_CHANNEL_NUM, \
                             AUDIO_CHANNEL_CONFIG_FRONT_CENTER, 0x00), \
    TUD_AUDIO_DESC_TYPE_I_FORMAT( \
        CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, \
        CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX), \
    TUD_AUDIO_DESC_STD_AS_ISO_EP( \
        _epin, \
        (TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS | \
         TUSB_ISO_EP_ATT_DATA), \
        CFG_TUD_AUDIO_FUNC_1_FORMAT_1_EP_SZ_IN, 1), \
    TUD_AUDIO_DESC_CS_AS_ISO_EP( \
        AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO_CTRL_NONE, \
        AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_UNDEFINED, 0x0000)
