#include <assert.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "vk_input_native_platform.h"
#include "vk_input.h"
#include "vk_input_test.h"

const gpio_num_t vk_key_gpios[VK_KEY_COUNT]={0,18,17,16};
typedef struct {pthread_mutex_t mutex;pthread_cond_t condition;size_t length,item_size,head,count;bool deleted;uint8_t data[];} queue_t;
typedef struct {pthread_mutex_t mutex;pthread_cond_t condition;unsigned count;bool deleted;} semaphore_t;
typedef struct {pthread_t thread;void(*entry)(void*);void*argument;} task_t;
static atomic_uint g_create_count,g_fail_create,g_abort_count,g_publish_count,g_session;
static atomic_uint g_prepare_count,g_release_count,g_cancel_count,g_stop_count,g_error_count,g_fail_epoch_count,g_state_count;
static atomic_int g_prepare_result,g_release_result,g_cancel_result,g_stop_result,g_abort_result;
static atomic_bool g_audio_tainted,g_runtime_failure,g_retry_once,g_stop_block,g_stop_entered;
static vk_usb_input_handler_registration_t g_input;
static vk_usb_input_lifecycle_registration_t g_lifecycle;
typedef struct {vk_usb_button_event_t value;uint32_t epoch;} sent_t;
static pthread_mutex_t g_sent_mutex=PTHREAD_MUTEX_INITIALIZER;
static sent_t g_sent[128];static size_t g_sent_count;

static struct timespec deadline_ms(uint32_t timeout){struct timespec value;clock_gettime(CLOCK_REALTIME,&value);value.tv_sec+=timeout/1000U;value.tv_nsec+=(long)(timeout%1000U)*1000000L;if(value.tv_nsec>=1000000000L){++value.tv_sec;value.tv_nsec-=1000000000L;}return value;}
QueueHandle_t xQueueCreate(size_t length,size_t item_size){queue_t*q=calloc(1,sizeof(*q)+length*item_size);assert(q);pthread_mutex_init(&q->mutex,NULL);pthread_cond_init(&q->condition,NULL);q->length=length;q->item_size=item_size;return q;}
BaseType_t xQueueSend(QueueHandle_t handle,const void*item,TickType_t timeout){queue_t*q=handle;pthread_mutex_lock(&q->mutex);while(q->count==q->length&&!q->deleted&&timeout!=0U){struct timespec until=deadline_ms(timeout);if(pthread_cond_timedwait(&q->condition,&q->mutex,&until)!=0)break;}if(q->deleted||q->count==q->length){pthread_mutex_unlock(&q->mutex);return pdFALSE;}size_t at=(q->head+q->count)%q->length;memcpy(q->data+at*q->item_size,item,q->item_size);++q->count;pthread_cond_broadcast(&q->condition);pthread_mutex_unlock(&q->mutex);return pdTRUE;}
BaseType_t xQueueReceive(QueueHandle_t handle,void*item,TickType_t timeout){queue_t*q=handle;pthread_mutex_lock(&q->mutex);while(q->count==0U&&!q->deleted&&timeout!=0U){struct timespec until=deadline_ms(timeout);if(pthread_cond_timedwait(&q->condition,&q->mutex,&until)!=0)break;}if(q->deleted||q->count==0U){pthread_mutex_unlock(&q->mutex);return pdFALSE;}memcpy(item,q->data+q->head*q->item_size,q->item_size);q->head=(q->head+1U)%q->length;--q->count;pthread_cond_broadcast(&q->condition);pthread_mutex_unlock(&q->mutex);return pdTRUE;}
BaseType_t xQueueReset(QueueHandle_t handle){queue_t*q=handle;pthread_mutex_lock(&q->mutex);q->head=q->count=0U;pthread_cond_broadcast(&q->condition);pthread_mutex_unlock(&q->mutex);return pdTRUE;}
void vQueueDelete(QueueHandle_t handle){queue_t*q=handle;pthread_mutex_lock(&q->mutex);assert(!q->deleted);q->deleted=true;pthread_cond_broadcast(&q->condition);pthread_mutex_unlock(&q->mutex);pthread_cond_destroy(&q->condition);pthread_mutex_destroy(&q->mutex);free(q);}
SemaphoreHandle_t xSemaphoreCreateBinary(void){semaphore_t*s=calloc(1,sizeof(*s));assert(s);pthread_mutex_init(&s->mutex,NULL);pthread_cond_init(&s->condition,NULL);return s;}
SemaphoreHandle_t xSemaphoreCreateMutex(void){semaphore_t*s=xSemaphoreCreateBinary();s->count=1U;return s;}
BaseType_t xSemaphoreTake(SemaphoreHandle_t handle,TickType_t timeout){semaphore_t*s=handle;pthread_mutex_lock(&s->mutex);while(s->count==0U&&!s->deleted){if(timeout==portMAX_DELAY)pthread_cond_wait(&s->condition,&s->mutex);else{struct timespec until=deadline_ms(timeout);if(pthread_cond_timedwait(&s->condition,&s->mutex,&until)!=0)break;}}if(s->deleted||s->count==0U){pthread_mutex_unlock(&s->mutex);return pdFALSE;}--s->count;pthread_mutex_unlock(&s->mutex);return pdTRUE;}
BaseType_t xSemaphoreGive(SemaphoreHandle_t handle){semaphore_t*s=handle;pthread_mutex_lock(&s->mutex);assert(!s->deleted);++s->count;pthread_cond_broadcast(&s->condition);pthread_mutex_unlock(&s->mutex);return pdTRUE;}
void vSemaphoreDelete(SemaphoreHandle_t handle){semaphore_t*s=handle;pthread_mutex_lock(&s->mutex);assert(!s->deleted);s->deleted=true;pthread_cond_broadcast(&s->condition);pthread_mutex_unlock(&s->mutex);pthread_cond_destroy(&s->condition);pthread_mutex_destroy(&s->mutex);free(s);}
static void*run_task(void*value){task_t*t=value;t->entry(t->argument);return NULL;}
BaseType_t xTaskCreatePinnedToCore(void(*entry)(void*),const char*name,uint32_t stack,void*argument,uint32_t priority,TaskHandle_t*out,int core){(void)name;(void)stack;(void)priority;(void)core;unsigned ordinal=atomic_fetch_add(&g_create_count,1U)+1U;if(ordinal==atomic_load(&g_fail_create))return pdFALSE;task_t*t=calloc(1,sizeof(*t));assert(t);t->entry=entry;t->argument=argument;assert(pthread_create(&t->thread,NULL,run_task,t)==0);pthread_detach(t->thread);*out=t;return pdPASS;}
void vTaskDelete(TaskHandle_t task){(void)task;pthread_exit(NULL);}TickType_t xTaskGetTickCount(void){return 0U;}void vTaskDelayUntil(TickType_t*w,TickType_t increment){*w+=increment;struct timespec d={0,100000L};nanosleep(&d,NULL);}void vTaskDelay(TickType_t delay){(void)delay;struct timespec d={0,100000L};nanosleep(&d,NULL);}int gpio_get_level(gpio_num_t gpio){(void)gpio;return 1;}int64_t esp_timer_get_time(void){struct timespec v;clock_gettime(CLOCK_MONOTONIC,&v);return (int64_t)v.tv_sec*1000000LL+v.tv_nsec/1000LL;}
static esp_err_t audio_prepare(uint32_t*out){atomic_fetch_add(&g_prepare_count,1U);if(atomic_load(&g_prepare_result)!=ESP_OK)return atomic_load(&g_prepare_result);*out=atomic_fetch_add(&g_session,1U)+1U;return ESP_OK;}static esp_err_t audio_release(uint32_t s){atomic_fetch_add(&g_release_count,1U);return s?atomic_load(&g_release_result):ESP_ERR_INVALID_ARG;}static esp_err_t audio_cancel(uint32_t s){atomic_fetch_add(&g_cancel_count,1U);return s?atomic_load(&g_cancel_result):ESP_ERR_INVALID_ARG;}static esp_err_t audio_stop(void){atomic_fetch_add(&g_stop_count,1U);atomic_store(&g_stop_entered,true);while(atomic_load(&g_stop_block))vTaskDelay(1U);return atomic_load(&g_stop_result);}static esp_err_t audio_abort(void){atomic_fetch_add(&g_abort_count,1U);return atomic_load(&g_abort_result);}static bool audio_active(void){return false;}static uint32_t audio_session(void){return 0U;}static bool audio_failure(uint32_t*s){if(!atomic_exchange(&g_runtime_failure,false))return false;*s=vk_input_test_session();return *s!=0U;}static const vk_audio_control_api_t audio_api={.prepare=audio_prepare,.release=audio_release,.cancel_prepared=audio_cancel,.stop=audio_stop,.abort=audio_abort,.is_active=audio_active,.session_id=audio_session,.take_runtime_failure=audio_failure};const vk_audio_control_api_t*vk_audio_control_api(void){return &audio_api;}bool vk_audio_is_tainted(void){return atomic_load(&g_audio_tainted);}
esp_err_t vk_usb_register_input_handler(const vk_usb_input_handler_registration_t*r){g_input=*r;return ESP_OK;}esp_err_t vk_usb_register_input_lifecycle(const vk_usb_input_lifecycle_registration_t*r){g_lifecycle=*r;return ESP_OK;}
vk_usb_handoff_result_t vk_usb_send_button(uint32_t e,const vk_usb_button_event_t*v){if(atomic_exchange(&g_retry_once,false))return VK_USB_HANDOFF_RETRY;pthread_mutex_lock(&g_sent_mutex);assert(g_sent_count<128U);g_sent[g_sent_count++]=(sent_t){.value=*v,.epoch=e};pthread_mutex_unlock(&g_sent_mutex);return e?VK_USB_HANDOFF_ACCEPTED:VK_USB_HANDOFF_EPOCH_CLOSED;}esp_err_t vk_usb_send_input_state(uint32_t e,vk_usb_input_mode_t m,vk_usb_key_t k){(void)m;(void)k;atomic_fetch_add(&g_state_count,1U);return e?ESP_OK:ESP_ERR_INVALID_STATE;}esp_err_t vk_usb_send_input_error(uint32_t e,vk_usb_input_error_t x){(void)x;atomic_fetch_add(&g_error_count,1U);return e?ESP_OK:ESP_ERR_INVALID_STATE;}esp_err_t vk_usb_fail_input_epoch(uint32_t e,vk_usb_input_error_t x){(void)e;(void)x;atomic_fetch_add(&g_fail_epoch_count,1U);return ESP_OK;}
static bool publish(void*context,const vk_usb_input_lifecycle_ack_t*ack){*(vk_usb_input_lifecycle_ack_t*)context=*ack;atomic_fetch_add(&g_publish_count,1U);return true;}
static void wait_uint(atomic_uint*v,unsigned expected){for(unsigned i=0;i<30000U&&atomic_load(v)<expected;++i)vTaskDelay(1U);assert(atomic_load(v)>=expected);}static void wait_sent(size_t expected){for(unsigned i=0;i<30000U;++i){pthread_mutex_lock(&g_sent_mutex);size_t n=g_sent_count;pthread_mutex_unlock(&g_sent_mutex);if(n>=expected)return;vTaskDelay(1U);}assert(false);}
static void reset(void){memset(&g_input,0,sizeof(g_input));memset(&g_lifecycle,0,sizeof(g_lifecycle));atomic_store(&g_create_count,0U);atomic_store(&g_fail_create,0U);atomic_store(&g_abort_count,0U);atomic_store(&g_publish_count,0U);atomic_store(&g_session,100U);atomic_store(&g_prepare_count,0U);atomic_store(&g_release_count,0U);atomic_store(&g_cancel_count,0U);atomic_store(&g_stop_count,0U);atomic_store(&g_error_count,0U);atomic_store(&g_state_count,0U);atomic_store(&g_fail_epoch_count,0U);atomic_store(&g_prepare_result,ESP_OK);atomic_store(&g_release_result,ESP_OK);atomic_store(&g_cancel_result,ESP_OK);atomic_store(&g_stop_result,ESP_OK);atomic_store(&g_abort_result,ESP_OK);atomic_store(&g_audio_tainted,false);atomic_store(&g_runtime_failure,false);atomic_store(&g_retry_once,false);atomic_store(&g_stop_block,false);atomic_store(&g_stop_entered,false);vk_input_test_force_join_timeout(false);pthread_mutex_lock(&g_sent_mutex);g_sent_count=0;pthread_mutex_unlock(&g_sent_mutex);}
static vk_usb_input_lifecycle_ack_t begin_epoch(uint32_t epoch){vk_usb_input_lifecycle_ack_t ack={0};vk_usb_input_lifecycle_sink_t sink={.publish=publish,.context=&ack};vk_usb_input_lifecycle_request_t r={.kind=VK_USB_INPUT_LIFECYCLE_NEW_EPOCH,.token=7U,.old_epoch=0U,.proposed_epoch=epoch,.lifecycle_generation=3U};assert(g_lifecycle.begin(g_lifecycle.context,&r,&sink)==VK_USB_INPUT_LIFECYCLE_ACCEPTED);wait_uint(&g_publish_count,1U);assert(ack.result==VK_USB_INPUT_LIFECYCLE_QUIESCENT&&vk_input_test_active_epoch()==epoch);return ack;}
static void finish_epoch(uint32_t epoch){vk_usb_input_lifecycle_ack_t ack={0};vk_usb_input_lifecycle_sink_t sink={.publish=publish,.context=&ack};vk_usb_input_lifecycle_request_t r={.kind=VK_USB_INPUT_LIFECYCLE_STOPPING,.token=8U,.old_epoch=epoch,.proposed_epoch=0U,.lifecycle_generation=4U};assert(g_lifecycle.begin(g_lifecycle.context,&r,&sink)==VK_USB_INPUT_LIFECYCLE_ACCEPTED);wait_uint(&g_publish_count,2U);assert(ack.result==VK_USB_INPUT_LIFECYCLE_QUIESCENT);assert(vk_input_stop()==ESP_OK);assert(vk_input_deinit()==ESP_OK);}
static vk_input_transition_t transition(vk_input_transition_kind_t kind,vk_input_key_t key,uint32_t duration){return(vk_input_transition_t){.kind=kind,.key=key,.duration_ms=duration};}
static void start_case(void){reset();assert(vk_input_init()==ESP_OK);assert(vk_input_start()==ESP_OK);(void)begin_epoch(9U);}
#if defined(VK_INPUT_STANDARD_MICROPHONE_TEST)
static void scenario_standard_microphone_forwards_all_keys(void){puts("input-standard-microphone: all keys are host events");start_case();assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K4,0)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_UP,VK_INPUT_KEY_K4,1600)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,1600)));wait_sent(3U);assert(atomic_load(&g_prepare_count)==0U);assert(atomic_load(&g_release_count)==0U);assert(atomic_load(&g_stop_count)==0U);pthread_mutex_lock(&g_sent_mutex);for(size_t i=0;i<3U;++i){assert(g_sent[i].value.key==VK_USB_KEY_K4);assert(!g_sent[i].value.has_session_id);}pthread_mutex_unlock(&g_sent_mutex);finish_epoch(9U);}
int main(void){scenario_standard_microphone_forwards_all_keys();return 0;}
#else
static void set_click_mode(void){vk_usb_input_command_t command={.kind=VK_USB_INPUT_COMMAND_MODE,.expected_epoch=9U,.mode=VK_USB_INPUT_MODE_CLICK_TO_TALK};assert(g_input.handle_command(g_input.context,&command)==ESP_OK);wait_uint(&g_state_count,1U);}
static void scenario_hold_success_retry_fifo(void){puts("input-production: hold-success-retry-fifo");start_case();atomic_store(&g_retry_once,true);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K4,0)));wait_uint(&g_release_count,1U);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_UP,VK_INPUT_KEY_K4,1600)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,1600)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K1,0)));wait_uint(&g_stop_count,1U);wait_sent(4U);pthread_mutex_lock(&g_sent_mutex);assert(g_sent[0].value.kind==VK_USB_BUTTON_DOWN&&g_sent[0].value.has_session_id);assert(g_sent[1].value.kind==VK_USB_BUTTON_UP&&g_sent[1].value.session_id==g_sent[0].value.session_id);assert(g_sent[2].value.kind==VK_USB_BUTTON_CLICK&&g_sent[2].value.session_id==g_sent[0].value.session_id);assert(g_sent[3].value.key==VK_USB_KEY_K1);pthread_mutex_unlock(&g_sent_mutex);finish_epoch(9U);}
static void scenario_release_failure_identity_no_duplicate(void){puts("input-production: release-failure-identity-no-duplicate");start_case();atomic_store(&g_release_result,ESP_FAIL);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K4,0)));wait_uint(&g_cancel_count,1U);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_UP,VK_INPUT_KEY_K4,100)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,100)));wait_sent(3U);pthread_mutex_lock(&g_sent_mutex);assert(g_sent_count==3U);uint32_t s=g_sent[0].value.session_id;assert(s!=0U&&g_sent[1].value.session_id==s&&g_sent[2].value.session_id==s);pthread_mutex_unlock(&g_sent_mutex);assert(atomic_load(&g_stop_count)==0U);finish_epoch(9U);}
static void scenario_prepare_failure_sessionless(void){puts("input-production: prepare-failure-sessionless");start_case();atomic_store(&g_prepare_result,ESP_FAIL);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K4,0)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_UP,VK_INPUT_KEY_K4,42)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,42)));wait_sent(3U);pthread_mutex_lock(&g_sent_mutex);for(size_t i=0;i<3U;++i)assert(!g_sent[i].value.has_session_id);pthread_mutex_unlock(&g_sent_mutex);wait_uint(&g_error_count,1U);finish_epoch(9U);}
static void scenario_runtime_failure_filters_voice(void){puts("input-production: runtime-failure-filters-voice");start_case();assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K4,0)));wait_uint(&g_release_count,1U);atomic_store(&g_runtime_failure,true);wait_uint(&g_error_count,1U);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_UP,VK_INPUT_KEY_K4,12)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K2,0)));wait_sent(2U);pthread_mutex_lock(&g_sent_mutex);assert(g_sent[0].value.key==VK_USB_KEY_K4&&g_sent[1].value.key==VK_USB_KEY_K2);pthread_mutex_unlock(&g_sent_mutex);finish_epoch(9U);}
static void scenario_mailboxes_full_reserved_abort_supersession(void){puts("input-production: mailbox-full-reserved-abort-supersession");start_case();assert(vk_input_test_fill_ordinary_mailboxes());vk_usb_input_lifecycle_ack_t old={0},fresh={0};vk_usb_input_lifecycle_sink_t a={.publish=publish,.context=&old},b={.publish=publish,.context=&fresh};vk_usb_input_lifecycle_request_t r={.kind=VK_USB_INPUT_LIFECYCLE_LEASE_EXPIRED,.token=11U,.old_epoch=9U,.proposed_epoch=0U,.lifecycle_generation=12U};assert(g_lifecycle.begin(g_lifecycle.context,&r,&a)==VK_USB_INPUT_LIFECYCLE_ACCEPTED);r.kind=VK_USB_INPUT_LIFECYCLE_STOPPING;r.token=13U;r.lifecycle_generation=14U;assert(g_lifecycle.begin(g_lifecycle.context,&r,&b)==VK_USB_INPUT_LIFECYCLE_ACCEPTED);wait_uint(&g_publish_count,2U);assert(fresh.token==13U&&fresh.result==VK_USB_INPUT_LIFECYCLE_QUIESCENT);assert(atomic_load(&g_abort_count)==1U);assert(vk_input_stop()==ESP_OK);assert(vk_input_deinit()==ESP_OK);}
static void scenario_stale_result_cannot_mutate(void){puts("input-production: stale-result-cannot-mutate");start_case();assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K4,0)));wait_uint(&g_release_count,1U);uint32_t session=vk_input_test_session();assert(session!=0U);assert(vk_input_test_inject_result(VK_INPUT_TEST_RESULT_RUNTIME_FAILED,8U,UINT32_MAX,session));vTaskDelay(20U);assert(vk_input_test_session()==session);assert(atomic_load(&g_error_count)==0U);finish_epoch(9U);}
static void scenario_click_stop_pending_third_restart(void){puts("input-production: click-stop-pending-third-restart");start_case();set_click_mode();assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,10)));wait_uint(&g_release_count,1U);atomic_store(&g_stop_block,true);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,20)));wait_uint(&g_stop_count,1U);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,30)));vTaskDelay(20U);assert(atomic_load(&g_prepare_count)==1U);atomic_store(&g_stop_block,false);wait_uint(&g_prepare_count,2U);assert(atomic_load(&g_stop_count)==1U);finish_epoch(9U);}
static void scenario_cancel_failure_terminal(void){puts("input-production: cancel-failure-terminal-epoch");start_case();atomic_store(&g_release_result,ESP_FAIL);atomic_store(&g_cancel_result,ESP_FAIL);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K4,0)));wait_uint(&g_fail_epoch_count,1U);assert(vk_input_is_tainted());assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K1,0)));vTaskDelay(20U);assert(g_sent_count<=1U);finish_epoch(9U);}
static void scenario_stop_failure_filters_voice(void){puts("input-production: stop-failure-stable-voice-filter");start_case();set_click_mode();assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,1)));wait_uint(&g_release_count,1U);atomic_store(&g_stop_result,ESP_FAIL);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,2)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_CLICK,VK_INPUT_KEY_K4,3)));assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K2,0)));wait_uint(&g_error_count,1U);wait_sent(3U);pthread_mutex_lock(&g_sent_mutex);assert(g_sent[g_sent_count-1U].value.key==VK_USB_KEY_K2);pthread_mutex_unlock(&g_sent_mutex);assert(atomic_load(&g_prepare_count)==1U);finish_epoch(9U);}
static void scenario_reserved_terminal_overflows(void){puts("input-production: result-and-fifo-overflow-terminal");start_case();vk_input_test_force_result_overflow();wait_uint(&g_fail_epoch_count,1U);assert(vk_input_is_tainted());finish_epoch(9U);start_case();assert(vk_input_test_fill_transition_fifo_and_overflow());wait_uint(&g_fail_epoch_count,1U);assert(vk_input_is_tainted());finish_epoch(9U);}
static void scenario_join_timeout_retains_ownership(void){puts("input-production: join-timeout-retains-ownership");start_case();finish_epoch(9U);/* Re-run with an injected bounded join timeout. */reset();assert(vk_input_init()==ESP_OK);assert(vk_input_start()==ESP_OK);(void)begin_epoch(9U);vk_usb_input_lifecycle_ack_t ack={0};vk_usb_input_lifecycle_sink_t sink={.publish=publish,.context=&ack};vk_usb_input_lifecycle_request_t r={.kind=VK_USB_INPUT_LIFECYCLE_STOPPING,.token=31U,.old_epoch=9U,.proposed_epoch=0U,.lifecycle_generation=32U};assert(g_lifecycle.begin(g_lifecycle.context,&r,&sink)==VK_USB_INPUT_LIFECYCLE_ACCEPTED);wait_uint(&g_publish_count,2U);vk_input_test_force_join_timeout(true);assert(vk_input_stop()==ESP_ERR_TIMEOUT);assert(vk_input_test_started());assert(vk_input_deinit()==ESP_ERR_INVALID_STATE);vk_input_test_force_join_timeout(false);assert(vk_input_stop()==ESP_OK);assert(vk_input_deinit()==ESP_OK);}
static void scenario_partial_start_join(void){puts("input-production: partial-start-joined-cleanup");for(unsigned failure=1U;failure<=3U;++failure){reset();assert(vk_input_init()==ESP_OK);atomic_store(&g_fail_create,failure);assert(vk_input_start()==ESP_ERR_NO_MEM);assert(!vk_input_test_started());assert(vk_input_deinit()==ESP_OK);}}
static void scenario_release_failure_ordinary(void){puts("input-production: release-failure-ordinary");start_case();atomic_store(&g_release_result,ESP_FAIL);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K4,0)));wait_uint(&g_cancel_count,1U);wait_uint(&g_error_count,1U);assert(atomic_load(&g_fail_epoch_count)==0U);assert(!vk_input_is_tainted());assert(vk_input_test_active_epoch()==9U);finish_epoch(9U);}
static void scenario_release_failure_tainted(void){puts("input-production: release-failure-tainted");start_case();atomic_store(&g_release_result,ESP_FAIL);atomic_store(&g_audio_tainted,true);assert(vk_input_test_enqueue_transition(transition(VK_INPUT_TRANSITION_DOWN,VK_INPUT_KEY_K4,0)));wait_uint(&g_fail_epoch_count,1U);assert(atomic_load(&g_cancel_count)==0U);assert(vk_input_is_tainted());finish_epoch(9U);}
int main(void){scenario_hold_success_retry_fifo();scenario_release_failure_identity_no_duplicate();scenario_prepare_failure_sessionless();scenario_runtime_failure_filters_voice();scenario_mailboxes_full_reserved_abort_supersession();scenario_stale_result_cannot_mutate();scenario_click_stop_pending_third_restart();scenario_cancel_failure_terminal();scenario_stop_failure_filters_voice();scenario_reserved_terminal_overflows();scenario_join_timeout_retains_ownership();scenario_partial_start_join();scenario_release_failure_ordinary();scenario_release_failure_tainted();return 0;}
#endif
