#include <assert.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "vk_input_native_platform.h"
#define TEST_LIFECYCLE_PENDING ((esp_err_t)0x7f01)
#include "vk_input.h"
#include "vk_input_test.h"

const gpio_num_t vk_key_gpios[VK_KEY_COUNT]={0,18,17,16};
typedef struct {pthread_mutex_t mutex;pthread_cond_t condition;size_t length,item_size,head,count;bool deleted;uint8_t data[];} queue_t;
typedef struct {pthread_mutex_t mutex;pthread_cond_t condition;unsigned count;bool deleted;} semaphore_t;
typedef struct {pthread_t thread;void(*entry)(void*);void*argument;} task_t;
static atomic_uint g_create_count,g_fail_create,g_abort_count,g_publish_count,g_session;
static atomic_uint g_prepare_count,g_release_count,g_cancel_count,g_stop_count,g_error_count,g_fail_epoch_count,g_state_count;
static atomic_int g_prepare_result,g_release_result,g_cancel_result,g_stop_result,g_abort_result;
static atomic_bool g_audio_tainted,g_runtime_failure,g_retry_once,g_stop_block,g_stop_entered;
static vk_usb_input_handler_registration_t g_input;
static vk_usb_input_lifecycle_registration_t g_lifecycle;
static vk_usb_service_t *g_service;
typedef struct { atomic_uint_fast64_t now; pthread_mutex_t mutex; uint8_t output[65536]; size_t output_count; } usb_fake_t;
static usb_fake_t g_usb;
typedef struct {vk_usb_button_event_t value;uint32_t epoch;} sent_t;
static pthread_mutex_t g_sent_mutex=PTHREAD_MUTEX_INITIALIZER;
static sent_t g_sent[128];static size_t g_sent_count;
static atomic_bool g_abort_block;
static pthread_mutex_t g_abort_mutex=PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t g_abort_cond=PTHREAD_COND_INITIALIZER;
static atomic_bool g_abort_entered;


static esp_err_t usb_install(void *context){(void)context;return ESP_OK;}
static esp_err_t usb_uninstall(void *context){(void)context;return ESP_OK;}
static int usb_read(void *context,uint8_t *bytes,size_t capacity,uint32_t timeout_ms){(void)context;(void)bytes;(void)capacity;(void)timeout_ms;return 0;}
static int usb_write(void *context,const uint8_t *bytes,size_t length,uint32_t timeout_ms){(void)timeout_ms;usb_fake_t*f=context;pthread_mutex_lock(&f->mutex);assert(f->output_count+length<=sizeof(f->output));memcpy(f->output+f->output_count,bytes,length);f->output_count+=length;pthread_mutex_unlock(&f->mutex);return(int)length;}
static uint64_t usb_now(void *context){return atomic_load(&((usb_fake_t*)context)->now);}
static void usb_lock(void *context){pthread_mutex_lock(&((usb_fake_t*)context)->mutex);}
static void usb_unlock(void *context){pthread_mutex_unlock(&((usb_fake_t*)context)->mutex);}
static void service_create(void){memset(&g_usb,0,sizeof(g_usb));pthread_mutex_init(&g_usb.mutex,NULL);g_service=calloc(1,vk_usb_service_size());assert(g_service);vk_usb_transport_ops_t ops={usb_install,usb_uninstall,usb_read,usb_write,usb_now,usb_lock,usb_unlock,&g_usb};vk_usb_identity_t identity={"vibe_keyboard","test","USB-INPUT"};vk_usb_service_policy_t policy={0};assert(vk_usb_service_init(g_service,&ops,&identity,&policy)==ESP_OK);}
static void service_open_epoch(uint32_t epoch){assert(vk_usb_service_start(g_service)==ESP_OK);vk_usb_service_set_epoch_for_test(g_service,epoch);/* Native setter changes identity only; use a real transport event to open admission. */static const uint8_t frame[]={1,0x10,34,0,'{','"','e','v','e','n','t','"',':','"','t','r','a','n','s','p','o','r','t','"',',','"','k','i','n','d','"',':','"','u','s','b','"','}'};assert(vk_usb_service_consume_for_test(g_service,frame,sizeof(frame))==ESP_OK);for(unsigned i=0;i<30000U&&!vk_usb_service_has_epoch(g_service);++i){esp_err_t e=vk_usb_service_process_lifecycle(g_service);assert(e==ESP_OK||e==TEST_LIFECYCLE_PENDING);vTaskDelay(1U);}assert(vk_usb_service_has_epoch(g_service));}
static struct timespec deadline_ms(uint32_t timeout){struct timespec value;clock_gettime(CLOCK_REALTIME,&value);value.tv_sec+=timeout/1000U;value.tv_nsec+=(long)(timeout%1000U)*1000000L;if(value.tv_nsec>=1000000000L){++value.tv_sec;value.tv_nsec-=1000000000L;}return value;}
QueueHandle_t xQueueCreate(size_t length,size_t item_size){queue_t*q=calloc(1,sizeof(*q)+length*item_size);assert(q);pthread_mutex_init(&q->mutex,NULL);pthread_cond_init(&q->condition,NULL);q->length=length;q->item_size=item_size;return q;}
BaseType_t xQueueSend(QueueHandle_t handle,const void*item,TickType_t timeout){queue_t*q=handle;pthread_mutex_lock(&q->mutex);while(q->count==q->length&&!q->deleted&&timeout!=0U){struct timespec until=deadline_ms(timeout);if(pthread_cond_timedwait(&q->condition,&q->mutex,&until)!=0)break;}if(q->deleted||q->count==q->length){pthread_mutex_unlock(&q->mutex);return pdFALSE;}size_t at=(q->head+q->count)%q->length;memcpy(q->data+at*q->item_size,item,q->item_size);++q->count;pthread_cond_broadcast(&q->condition);pthread_mutex_unlock(&q->mutex);return pdTRUE;}
BaseType_t xQueueReceive(QueueHandle_t handle,void*item,TickType_t timeout){queue_t*q=handle;pthread_mutex_lock(&q->mutex);while(q->count==0U&&!q->deleted&&timeout!=0U){struct timespec until=deadline_ms(timeout);if(pthread_cond_timedwait(&q->condition,&q->mutex,&until)!=0)break;}if(q->deleted||q->count==0U){pthread_mutex_unlock(&q->mutex);return pdFALSE;}memcpy(item,q->data+q->head*q->item_size,q->item_size);q->head=(q->head+1U)%q->length;--q->count;pthread_cond_broadcast(&q->condition);pthread_mutex_unlock(&q->mutex);return pdTRUE;}
BaseType_t xQueueReset(QueueHandle_t handle){queue_t*q=handle;pthread_mutex_lock(&q->mutex);q->head=q->count=0U;pthread_cond_broadcast(&q->condition);pthread_mutex_unlock(&q->mutex);return pdTRUE;}
void vQueueDelete(QueueHandle_t handle){queue_t*q=handle;pthread_mutex_lock(&q->mutex);assert(!q->deleted);q->deleted=true;pthread_cond_broadcast(&q->condition);pthread_mutex_unlock(&q->mutex);pthread_cond_destroy(&q->condition);pthread_mutex_destroy(&q->mutex);free(q);}
SemaphoreHandle_t xSemaphoreCreateBinary(void){semaphore_t*s=calloc(1,sizeof(*s));assert(s);pthread_mutex_init(&s->mutex,NULL);pthread_cond_init(&s->condition,NULL);return s;}
SemaphoreHandle_t xSemaphoreCreateMutex(void){semaphore_t*s=xSemaphoreCreateBinary();s->count=1U;return s;}
BaseType_t xSemaphoreTake(SemaphoreHandle_t handle,TickType_t timeout){semaphore_t*s=handle;pthread_mutex_lock(&s->mutex);while(s->count==0U&&!s->deleted){if(timeout==portMAX_DELAY)pthread_cond_wait(&s->condition,&s->mutex);else{struct timespec until=deadline_ms(timeout);if(pthread_cond_timedwait(&s->condition,&s->mutex,&until)!=0)break;}}if(s->deleted||s->count==0U){pthread_mutex_unlock(&s->mutex);return pdFALSE;}--s->count;pthread_mutex_unlock(&s->mutex);return pdTRUE;}
BaseType_t xSemaphoreGive(SemaphoreHandle_t handle){semaphore_t*s=handle;pthread_mutex_lock(&s->mutex);assert(!s->deleted);++s->count;pthread_cond_broadcast(&s->condition);pthread_mutex_unlock(&s->mutex);return pdTRUE;}
void vSemaphoreDelete(SemaphoreHandle_t handle){semaphore_t*s=handle;pthread_mutex_lock(&s->mutex);assert(!s->deleted);s->deleted=true;pthread_cond_broadcast(&s->condition);pthread_mutex_unlock(&s->mutex);pthread_cond_destroy(&s->condition);pthread_mutex_destroy(&s->mutex);free(s);}
static void*run_task(void*value){task_t*t=value;t->entry(t->argument);return NULL;}
BaseType_t xTaskCreatePinnedToCore(void(*entry)(void*),const char*name,uint32_t stack,void*argument,uint32_t priority,TaskHandle_t*out,int core){(void)name;(void)stack;(void)priority;(void)core;unsigned ordinal=atomic_fetch_add(&g_create_count,1U)+1U;if(ordinal==atomic_load(&g_fail_create))return pdFALSE;task_t*t=calloc(1,sizeof(*t));assert(t);t->entry=entry;t->argument=argument;assert(pthread_create(&t->thread,NULL,run_task,t)==0);pthread_detach(t->thread);*out=t;return pdPASS;}
void vTaskDelete(TaskHandle_t task){(void)task;pthread_exit(NULL);}TickType_t xTaskGetTickCount(void){return 0U;}void vTaskDelayUntil(TickType_t*w,TickType_t increment){*w+=increment;struct timespec d={0,100000L};nanosleep(&d,NULL);}void vTaskDelay(TickType_t delay){(void)delay;struct timespec d={0,100000L};nanosleep(&d,NULL);}int gpio_get_level(gpio_num_t gpio){(void)gpio;return 1;}int64_t esp_timer_get_time(void){struct timespec v;clock_gettime(CLOCK_MONOTONIC,&v);return (int64_t)v.tv_sec*1000000LL+v.tv_nsec/1000LL;}
static esp_err_t audio_prepare(uint32_t*out){atomic_fetch_add(&g_prepare_count,1U);if(atomic_load(&g_prepare_result)!=ESP_OK)return atomic_load(&g_prepare_result);*out=atomic_fetch_add(&g_session,1U)+1U;return ESP_OK;}static esp_err_t audio_release(uint32_t s){atomic_fetch_add(&g_release_count,1U);return s?atomic_load(&g_release_result):ESP_ERR_INVALID_ARG;}static esp_err_t audio_cancel(uint32_t s){atomic_fetch_add(&g_cancel_count,1U);return s?atomic_load(&g_cancel_result):ESP_ERR_INVALID_ARG;}static esp_err_t audio_stop(void){atomic_fetch_add(&g_stop_count,1U);atomic_store(&g_stop_entered,true);while(atomic_load(&g_stop_block))vTaskDelay(1U);return atomic_load(&g_stop_result);}static esp_err_t audio_abort(void){atomic_fetch_add(&g_abort_count,1U);atomic_store(&g_abort_entered,true);pthread_mutex_lock(&g_abort_mutex);while(atomic_load(&g_abort_block))pthread_cond_wait(&g_abort_cond,&g_abort_mutex);pthread_mutex_unlock(&g_abort_mutex);return atomic_load(&g_abort_result);}static bool audio_active(void){return false;}static uint32_t audio_session(void){return 0U;}static bool audio_failure(uint32_t*s){if(!atomic_exchange(&g_runtime_failure,false))return false;*s=vk_input_test_session();return *s!=0U;}static const vk_audio_control_api_t audio_api={.prepare=audio_prepare,.release=audio_release,.cancel_prepared=audio_cancel,.stop=audio_stop,.abort=audio_abort,.is_active=audio_active,.session_id=audio_session,.take_runtime_failure=audio_failure};const vk_audio_control_api_t*vk_audio_control_api(void){return &audio_api;}bool vk_audio_is_tainted(void){return atomic_load(&g_audio_tainted);}
esp_err_t vk_usb_register_input_handler(const vk_usb_input_handler_registration_t*r){g_input=*r;return vk_usb_service_register_input_handler(g_service,r);}esp_err_t vk_usb_register_input_lifecycle(const vk_usb_input_lifecycle_registration_t*r){g_lifecycle=*r;return vk_usb_service_register_input_lifecycle(g_service,r);}
vk_usb_handoff_result_t vk_usb_send_button(uint32_t e,const vk_usb_button_event_t*v){if(atomic_exchange(&g_retry_once,false))return VK_USB_HANDOFF_RETRY;vk_usb_handoff_result_t r=vk_usb_service_send_button_for_epoch(g_service,e,v);if(r==VK_USB_HANDOFF_ACCEPTED){pthread_mutex_lock(&g_sent_mutex);assert(g_sent_count<128U);g_sent[g_sent_count++]=(sent_t){.value=*v,.epoch=e};pthread_mutex_unlock(&g_sent_mutex);}return r;}esp_err_t vk_usb_send_input_state(uint32_t e,vk_usb_input_mode_t m,vk_usb_key_t k){atomic_fetch_add(&g_state_count,1U);return vk_usb_service_send_input_state_for_epoch(g_service,e,m,k);}esp_err_t vk_usb_send_input_error(uint32_t e,vk_usb_input_error_t x){atomic_fetch_add(&g_error_count,1U);return vk_usb_service_send_input_error_for_epoch(g_service,e,x);}esp_err_t vk_usb_fail_input_epoch(uint32_t e,vk_usb_input_error_t x){atomic_fetch_add(&g_fail_epoch_count,1U);return vk_usb_service_fail_input_epoch(g_service,e,x);}
static bool publish(void*context,const vk_usb_input_lifecycle_ack_t*ack){*(vk_usb_input_lifecycle_ack_t*)context=*ack;atomic_fetch_add(&g_publish_count,1U);return true;}
static void reset(void){memset(&g_input,0,sizeof(g_input));memset(&g_lifecycle,0,sizeof(g_lifecycle));atomic_store(&g_create_count,0U);atomic_store(&g_fail_create,0U);atomic_store(&g_abort_count,0U);atomic_store(&g_publish_count,0U);atomic_store(&g_session,100U);atomic_store(&g_prepare_count,0U);atomic_store(&g_release_count,0U);atomic_store(&g_cancel_count,0U);atomic_store(&g_stop_count,0U);atomic_store(&g_error_count,0U);atomic_store(&g_state_count,0U);atomic_store(&g_fail_epoch_count,0U);atomic_store(&g_prepare_result,ESP_OK);atomic_store(&g_release_result,ESP_OK);atomic_store(&g_cancel_result,ESP_OK);atomic_store(&g_stop_result,ESP_OK);atomic_store(&g_abort_result,ESP_OK);atomic_store(&g_audio_tainted,false);atomic_store(&g_runtime_failure,false);atomic_store(&g_retry_once,false);atomic_store(&g_stop_block,false);atomic_store(&g_stop_entered,false);vk_input_test_force_join_timeout(false);atomic_store(&g_abort_block,false);atomic_store(&g_abort_entered,false);pthread_mutex_lock(&g_sent_mutex);g_sent_count=0;pthread_mutex_unlock(&g_sent_mutex);}
static void start_case(void){reset();service_create();assert(vk_input_init()==ESP_OK);assert(vk_input_start()==ESP_OK);service_open_epoch(9U);assert(vk_input_test_active_epoch()==vk_usb_service_epoch(g_service));}
typedef struct {pthread_mutex_t mutex;pthread_cond_t condition;bool entered,release;} gate_t;
static void command_gate(void *context){gate_t*g=context;pthread_mutex_lock(&g->mutex);g->entered=true;pthread_cond_broadcast(&g->condition);while(!g->release)pthread_cond_wait(&g->condition,&g->mutex);pthread_mutex_unlock(&g->mutex);}
static void *command_thread(void *unused){(void)unused;static const char json[]="{\"event\":\"interaction_mode\",\"mode\":\"click_to_talk\"}";uint8_t frame[4+sizeof(json)-1];frame[0]=1;frame[1]=0x10;frame[2]=(uint8_t)(sizeof(json)-1);frame[3]=0;memcpy(frame+4,json,sizeof(json)-1);return(void*)(intptr_t)vk_usb_service_consume_for_test(g_service,frame,sizeof(frame));}
static void *lifecycle_thread(void *unused){(void)unused;static const uint8_t frame[]={1,0x10,34,0,'{','"','e','v','e','n','t','"',':','"','t','r','a','n','s','p','o','r','t','"',',','"','k','i','n','d','"',':','"','u','s','b','"','}'};return(void*)(intptr_t)vk_usb_service_consume_for_test(g_service,frame,sizeof(frame));}
static void local_quiesce(uint32_t epoch){unsigned before=atomic_load(&g_publish_count);vk_usb_input_lifecycle_ack_t ack={0};vk_usb_input_lifecycle_sink_t sink={publish,&ack};vk_usb_input_lifecycle_request_t request={VK_USB_INPUT_LIFECYCLE_STOPPING,91U,epoch,0U,92U,3250U};assert(g_lifecycle.begin(g_lifecycle.context,&request,&sink)==VK_USB_INPUT_LIFECYCLE_ACCEPTED);for(unsigned i=0;i<30000U&&atomic_load(&g_publish_count)==before;++i)vTaskDelay(1U);assert(atomic_load(&g_publish_count)>before);assert(ack.result==VK_USB_INPUT_LIFECYCLE_QUIESCENT);}
static void scenario_callback_lifecycle_barrier(void){puts("usb-input-integration: callback-lifecycle-deinit-barrier");start_case();gate_t gate={.mutex=PTHREAD_MUTEX_INITIALIZER,.condition=PTHREAD_COND_INITIALIZER};vk_input_test_set_command_hook(command_gate,&gate);pthread_t command,lifecycle;pthread_create(&command,NULL,command_thread,NULL);pthread_mutex_lock(&gate.mutex);while(!gate.entered)pthread_cond_wait(&gate.condition,&gate.mutex);pthread_mutex_unlock(&gate.mutex);pthread_create(&lifecycle,NULL,lifecycle_thread,NULL);vTaskDelay(20U);assert(atomic_load(&g_publish_count)==0U);assert(vk_input_deinit()==ESP_ERR_INVALID_STATE);pthread_mutex_lock(&gate.mutex);gate.release=true;pthread_cond_broadcast(&gate.condition);pthread_mutex_unlock(&gate.mutex);void*r;pthread_join(command,&r);assert((esp_err_t)(intptr_t)r==ESP_OK);pthread_join(lifecycle,&r);assert((esp_err_t)(intptr_t)r==ESP_OK);vk_input_test_set_command_hook(NULL,NULL);local_quiesce(vk_input_test_active_epoch());assert(vk_input_stop()==ESP_OK);assert(vk_input_deinit()==ESP_OK);free(g_service);pthread_mutex_destroy(&g_usb.mutex);}
typedef struct { uint64_t target_total; } deadline_compose_ctx_t;
static void deadline_compose_hook(void *context,vk_input_test_lifecycle_stage_t stage){uint64_t now;if(stage==VK_INPUT_TEST_LIFECYCLE_BEFORE_ABORT){now=atomic_load(&g_usb.now);atomic_store(&g_usb.now,now+1500U);atomic_store(&g_abort_block,true);}else if(stage==VK_INPUT_TEST_LIFECYCLE_BEFORE_PUBLISH){deadline_compose_ctx_t*ctx=context;atomic_store(&g_usb.now,ctx->target_total);}}
static void scenario_deadline_composition(uint64_t total_ms,bool accepted){printf("usb-input-integration: deadline-compose-%llu-%s\n",(unsigned long long)total_ms,accepted?"accept":"taint");start_case();deadline_compose_ctx_t ctx={total_ms};vk_input_test_set_lifecycle_hook(deadline_compose_hook,&ctx);uint32_t old=vk_usb_service_epoch(g_service);atomic_store(&g_usb.now,0U);static const uint8_t frame[]={1,0x10,34,0,'{','"','e','v','e','n','t','"',':','"','t','r','a','n','s','p','o','r','t','"',',','"','k','i','n','d','"',':','"','u','s','b','"','}'};assert(vk_usb_service_consume_for_test(g_service,frame,sizeof(frame))==ESP_OK);for(unsigned i=0;i<30000U;++i){if(atomic_load(&g_abort_entered)){uint64_t advance=atomic_load(&g_usb.now)+1500U;atomic_store(&g_usb.now,advance);pthread_mutex_lock(&g_abort_mutex);atomic_store(&g_abort_block,false);pthread_cond_broadcast(&g_abort_cond);pthread_mutex_unlock(&g_abort_mutex);atomic_store(&g_abort_entered,false);}esp_err_t e=vk_usb_service_process_lifecycle(g_service);if(e==ESP_OK||e==ESP_ERR_TIMEOUT)break;assert(e==TEST_LIFECYCLE_PENDING);vTaskDelay(1U);}if(accepted){assert(!vk_usb_service_is_tainted(g_service));assert(vk_usb_service_has_epoch(g_service));assert(vk_usb_service_epoch(g_service)!=old);}else{assert(vk_usb_service_is_tainted(g_service));assert(!vk_usb_service_has_epoch(g_service));}vk_input_test_set_lifecycle_hook(NULL,NULL);local_quiesce(vk_input_test_active_epoch());assert(vk_input_stop()==ESP_OK);assert(vk_input_deinit()==ESP_OK);free(g_service);pthread_mutex_destroy(&g_usb.mutex);}
int main(void){scenario_callback_lifecycle_barrier();scenario_deadline_composition(3248U,true);scenario_deadline_composition(3250U,false);scenario_deadline_composition(3251U,false);return 0;}
