#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include "vk_usb_runtime.h"

typedef struct { esp_err_t prepare,create,startup,runtime,cleanup; bool started,stopped; int release,request; } fake_t;
static esp_err_t prep(void*c){return((fake_t*)c)->prepare;}static esp_err_t create(void*c){return((fake_t*)c)->create;}static bool started(void*c,uint32_t t){(void)t;return((fake_t*)c)->started;}static void request(void*c){++((fake_t*)c)->request;}static bool stopped(void*c,uint32_t t){(void)t;return((fake_t*)c)->stopped;}static esp_err_t startup(void*c){return((fake_t*)c)->startup;}static esp_err_t runtime(void*c){return((fake_t*)c)->runtime;}static esp_err_t cleanup(void*c){return((fake_t*)c)->cleanup;}static void release(void*c){++((fake_t*)c)->release;}
static vk_usb_runtime_t make(fake_t*f){vk_usb_runtime_ops_t o={prep,create,started,request,stopped,startup,runtime,cleanup,release,f};vk_usb_runtime_t r;vk_usb_runtime_init(&r,&o);return r;}
int main(void){fake_t p={.prepare=ESP_FAIL};vk_usb_runtime_t r=make(&p);assert(vk_usb_runtime_start(&r)==ESP_FAIL&&p.release==0);fake_t c={.create=ESP_FAIL};r=make(&c);assert(vk_usb_runtime_start(&r)==ESP_FAIL&&c.release==1);fake_t late={.started=false,.stopped=false};r=make(&late);assert(vk_usb_runtime_start(&r)==ESP_ERR_TIMEOUT&&vk_usb_runtime_is_tainted(&r)&&late.release==0);fake_t ct={.stopped=true};r=make(&ct);assert(vk_usb_runtime_start(&r)==ESP_ERR_TIMEOUT&&ct.release==1);fake_t sf={.started=true,.stopped=true,.startup=ESP_FAIL};r=make(&sf);assert(vk_usb_runtime_start(&r)==ESP_FAIL&&sf.release==1);fake_t clean={.started=true,.stopped=true,.runtime=ESP_FAIL};r=make(&clean);assert(vk_usb_runtime_start(&r)==ESP_OK);assert(vk_usb_runtime_stop(&r)==ESP_FAIL&&clean.release==1&&!vk_usb_runtime_is_tainted(&r));assert(vk_usb_runtime_start(&r)==ESP_OK);assert(vk_usb_runtime_stop(&r)==ESP_FAIL);fake_t dirty={.started=true,.stopped=true,.runtime=ESP_FAIL,.cleanup=ESP_ERR_INVALID_STATE};r=make(&dirty);assert(vk_usb_runtime_start(&r)==ESP_OK);assert(vk_usb_runtime_stop(&r)==ESP_ERR_INVALID_STATE&&dirty.release==0&&vk_usb_runtime_is_tainted(&r));assert(vk_usb_runtime_start(&r)==ESP_ERR_INVALID_STATE);fake_t timeout={.started=true,.stopped=false};r=make(&timeout);assert(vk_usb_runtime_start(&r)==ESP_OK);assert(vk_usb_runtime_stop(&r)==ESP_ERR_TIMEOUT&&timeout.release==0&&vk_usb_runtime_is_tainted(&r));puts("vk_usb runtime native tests passed");}
