#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <string.h>
#include "vk_usb.h"

typedef struct { uint8_t input[131072];size_t input_count,input_offset,read_limit;uint8_t output[262144];size_t output_count,write_limit,write_calls,write_fail_after;int write_mode,read_mode,install_count,uninstall_count,locks;bool install_fail,uninstall_fail;atomic_uint_fast64_t now_ms;pthread_mutex_t mutex; } fake_t;
static esp_err_t install(void*c){fake_t*f=c;++f->install_count;return f->install_fail?ESP_FAIL:ESP_OK;}static esp_err_t uninstall(void*c){fake_t*f=c;++f->uninstall_count;return f->uninstall_fail?ESP_FAIL:ESP_OK;}static int readf(void*c,uint8_t*b,size_t cap,uint32_t t){(void)t;fake_t*f=c;if(f->read_mode<0)return-1;if(f->read_mode>0)return(int)cap+1;size_t n=f->input_count-f->input_offset;if(n>cap)n=cap;if(f->read_limit&&n>f->read_limit)n=f->read_limit;memcpy(b,f->input+f->input_offset,n);f->input_offset+=n;return(int)n;}static int writef(void*c,const uint8_t*b,size_t n,uint32_t t){(void)t;fake_t*f=c;++f->write_calls;if(f->write_fail_after&&f->write_calls>=f->write_fail_after)return-1;if(f->write_mode<0)return-1;if(f->write_mode==1)return 0;if(f->write_mode==2)return(int)n+1;if(f->write_limit&&n>f->write_limit)n=f->write_limit;assert(f->output_count+n<=sizeof(f->output));memcpy(f->output+f->output_count,b,n);f->output_count+=n;return(int)n;}static uint64_t now(void*c){return atomic_load(&((fake_t*)c)->now_ms);}static void lock(void*c){fake_t*f=c;pthread_mutex_lock(&f->mutex);++f->locks;}static void unlock(void*c){fake_t*f=c;--f->locks;pthread_mutex_unlock(&f->mutex);}
static vk_usb_service_t*make_policy(fake_t*f,bool enabled){assert(pthread_mutex_init(&f->mutex,NULL)==0);vk_usb_service_t*s=calloc(1,vk_usb_service_size());assert(s);vk_usb_transport_ops_t o={install,uninstall,readf,writef,now,lock,unlock,f};vk_usb_identity_t i={"vibe_keyboard","test","VS-TEST"};vk_usb_service_policy_t p={.update_boot_policy_enabled=enabled};assert(vk_usb_service_init(s,&o,&i,&p)==ESP_OK);return s;}static vk_usb_service_t*make(fake_t*f){return make_policy(f,false);}static void bytes(fake_t*f,const uint8_t*b,size_t n){assert(f->input_count+n<=sizeof(f->input));memcpy(f->input+f->input_count,b,n);f->input_count+=n;}static void frame_t(fake_t*f,uint8_t type,const uint8_t*b,size_t n){uint8_t h[]={1,type,(uint8_t)n,(uint8_t)(n>>8)};bytes(f,h,4);bytes(f,b,n);}static void frame(fake_t*f,const char*j){frame_t(f,0x10,(const uint8_t*)j,strlen(j));}static void poll(vk_usb_service_t*s){assert(vk_usb_service_poll(s)==ESP_OK);}static void all(vk_usb_service_t*s,fake_t*f){size_t g=0;do{poll(s);assert(++g<200000);}while(f->input_offset<f->input_count);}static bool contains(fake_t*f,const char*t){size_t n=strlen(t);for(size_t i=0;i+n<=f->output_count;++i)if(memcmp(f->output+i,t,n)==0)return true;return false;}static void reset_in(fake_t*f){f->input_count=f->input_offset=0;}static void epoch(vk_usb_service_t*s,fake_t*f){frame(f,"{\"event\":\"transport\",\"kind\":\"usb\"}");all(s,f);assert(vk_usb_service_has_epoch(s));}

static void test_unicode(void){const char*bad[]={"{\"event\":\"ping\\u0000x\"}","{\"event\":\"transport\",\"kind\":\"usb\\u0000x\"}","{\"event\":\"ui_state\",\"state\":\"ready\\u0000x\",\"text\":\"x\"}","{\"event\\u0000x\":\"ping\"}","{\"event\":\"vk_asset_begin\",\"transfer_id\":1,\"sha256\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"total_bytes\":1,\"kind\":\"image\\u0000x\"}","{\"event\":\"\\uD800\"}","{\"event\":\"\\uDC00\"}"};static const uint8_t raw0[]={'{','"','e','v','e','n','t','"',':','"',0,'"','}'};static const uint8_t high[]={ '{','"','e','v','e','n','t','"',':','"',0xf4,0x90,0x80,0x80,'"','}' };fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);for(size_t i=0;i<sizeof(bad)/sizeof(*bad);++i)frame(&f,bad[i]);frame_t(&f,0x10,raw0,sizeof(raw0));frame_t(&f,0x10,high,sizeof(high));frame(&f,"{\"event\":\"transport\",\"kind\":\"us\\u0062\"}");all(s,&f);assert(vk_usb_service_has_epoch(s));reset_in(&f);frame(&f,"{\"event\":\"ui_state\",\"state\":\"ready\",\"text\":\"\\uD83D\\uDE00\"}");all(s,&f);assert(vk_usb_service_stop(s)==ESP_OK);free(s);}

static int provider_calls;static fake_t*provider_fake;static vk_usb_capability_snapshot_t provider_snapshot;static esp_err_t provider_result;
static esp_err_t capability_provider(void*c,uint32_t epoch,vk_usb_capability_snapshot_t*out){(void)c;assert(epoch!=0U);assert(provider_fake==NULL||provider_fake->locks==0);++provider_calls;if(provider_result==ESP_OK)*out=provider_snapshot;return provider_result;}
static void register_provider(vk_usb_service_t*s){vk_usb_capability_provider_registration_t r={capability_provider,NULL};assert(vk_usb_service_register_capability_provider(s,&r)==ESP_OK);}
static int input_commands;static vk_usb_input_command_t last_input_command;
static esp_err_t on_input_command(void*c,const vk_usb_input_command_t*x){(void)c;++input_commands;last_input_command=*x;return ESP_OK;}
static int commands,chunks;static esp_err_t command_result=ESP_OK,chunk_result=ESP_OK;static vk_usb_asset_command_t last_cmd;static vk_usb_asset_chunk_t last_chunk;static esp_err_t oncmd(void*c,const vk_usb_asset_command_t*x){(void)c;++commands;last_cmd=*x;return command_result;}static esp_err_t onchunk(void*c,const vk_usb_asset_chunk_t*x){(void)c;++chunks;last_chunk=*x;return chunk_result;}
static int update_commands,update_chunks;static vk_usb_update_command_t last_update_cmd;static vk_usb_update_chunk_t last_update_chunk;static bool tuple_available=true;static esp_err_t on_update_cmd(void*c,const vk_usb_update_command_t*x){(void)c;++update_commands;last_update_cmd=*x;return ESP_OK;}static esp_err_t on_update_chunk(void*c,const vk_usb_update_chunk_t*x){(void)c;++update_chunks;last_update_chunk=*x;return ESP_OK;}static bool update_tuple(void*c){(void)c;return tuple_available;}static void register_update_rejected(vk_usb_service_t*s){vk_usb_update_handler_registration_t r={on_update_cmd,on_update_chunk,update_tuple,NULL,4,10};assert(vk_usb_service_register_update_handler(s,&r)==ESP_ERR_NOT_SUPPORTED);}
static void register_asset(vk_usb_service_t*s){vk_usb_asset_handler_registration_t r={.handle_command=oncmd,.handle_chunk=onchunk,.context=NULL,.chunk_bytes=4,.max_asset_bytes=1000,.get_transfer_state=NULL};assert(vk_usb_service_register_asset_handler(s,&r)==ESP_OK);provider_snapshot=(vk_usb_capability_snapshot_t){0};provider_snapshot.assets=(vk_usb_assets_capability_t){.state=VK_USB_CAPABILITY_AVAILABLE,.storage_state=VK_USB_STORAGE_READY,.free_bytes=2000,.reserve_bytes=1,.upload_max_bytes=1000,.max_asset_bytes=1000,.chunk_bytes=4,.max_assets=1,.max_frames=1,.min_frame_ms=1,.max_frame_ms=1,.max_active_decoded_bytes=1,.decoder_scratch_bytes=1};provider_result=ESP_OK;register_provider(s);}
static void authorize(vk_usb_service_t*s,fake_t*f){reset_in(f);frame(f,"{\"event\":\"get_device_info\"}");all(s,f);reset_in(f);f->output_count=0;}

typedef struct { pthread_mutex_t mutex; pthread_cond_t condition; bool entered; bool release; bool alive; } provider_gate_t;
static esp_err_t blocking_provider(void *context,uint32_t epoch,vk_usb_capability_snapshot_t *snapshot)
{
    provider_gate_t *gate=context;assert(epoch!=0U);assert(pthread_mutex_lock(&gate->mutex)==0);
    assert(gate->alive);gate->entered=true;assert(pthread_cond_broadcast(&gate->condition)==0);
    while(!gate->release)assert(pthread_cond_wait(&gate->condition,&gate->mutex)==0);
    assert(gate->alive);assert(pthread_mutex_unlock(&gate->mutex)==0);*snapshot=(vk_usb_capability_snapshot_t){0};return ESP_OK;
}
typedef struct { vk_usb_service_t *service; fake_t *fake; esp_err_t result; } provider_refresh_t;
static void *refresh_provider(void *context)
{
    provider_refresh_t *refresh=context;reset_in(refresh->fake);frame(refresh->fake,"{\"event\":\"get_device_info\"}");
    refresh->result=vk_usb_service_poll(refresh->service);return NULL;
}
static void test_provider_lifetime_stop(void)
{
    fake_t f={0};provider_gate_t gate={.mutex=PTHREAD_MUTEX_INITIALIZER,.condition=PTHREAD_COND_INITIALIZER,.alive=true};
    vk_usb_service_t *service=make(&f);vk_usb_capability_provider_registration_t registration={blocking_provider,&gate};
    assert(vk_usb_service_register_capability_provider(service,&registration)==ESP_OK);assert(vk_usb_service_start(service)==ESP_OK);epoch(service,&f);
    provider_refresh_t refresh={service,&f,ESP_OK};pthread_t thread;assert(pthread_create(&thread,NULL,refresh_provider,&refresh)==0);
    assert(pthread_mutex_lock(&gate.mutex)==0);while(!gate.entered)assert(pthread_cond_wait(&gate.condition,&gate.mutex)==0);assert(pthread_mutex_unlock(&gate.mutex)==0);
    assert(vk_usb_service_stop(service)==ESP_ERR_TIMEOUT);assert(f.uninstall_count==0);
    assert(pthread_mutex_lock(&gate.mutex)==0);gate.release=true;assert(pthread_cond_broadcast(&gate.condition)==0);assert(pthread_mutex_unlock(&gate.mutex)==0);
    assert(pthread_join(thread,NULL)==0);assert(refresh.result==ESP_ERR_INVALID_STATE);
    assert(pthread_mutex_lock(&gate.mutex)==0);gate.alive=false;assert(pthread_mutex_unlock(&gate.mutex)==0);
    assert(vk_usb_service_stop(service)==ESP_OK);assert(f.uninstall_count==1);free(service);
}

static void test_capability_provider(void){
    fake_t f={0};provider_fake=&f;provider_calls=0;provider_result=ESP_OK;provider_snapshot=(vk_usb_capability_snapshot_t){0};
    provider_snapshot.update.state=VK_USB_CAPABILITY_UNAVAILABLE;provider_snapshot.update.unavailable_reason=VK_USB_UPDATE_REASON_BOOTLOADER_MIGRATION_REQUIRED;
    vk_usb_service_t*s=make(&f);register_provider(s);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);f.output_count=0;frame(&f,"{\"event\":\"get_device_info\"}");all(s,&f);assert(provider_calls==1);assert(contains(&f,"bootloader_migration_required"));
    provider_snapshot=(vk_usb_capability_snapshot_t){0};reset_in(&f);f.output_count=0;frame(&f,"{\"event\":\"get_device_info\"}");all(s,&f);assert(provider_calls==2);assert(!contains(&f,"bootloader_migration_required"));assert(contains(&f,"\"features\":{}"));
    provider_result=ESP_FAIL;provider_snapshot.update.state=VK_USB_CAPABILITY_UNAVAILABLE;reset_in(&f);f.output_count=0;frame(&f,"{\"event\":\"get_device_info\"}");all(s,&f);assert(provider_calls==3);assert(!contains(&f,"bootloader_migration_required"));assert(contains(&f,"\"features\":{}"));
    assert(vk_usb_service_stop(s)==ESP_OK);free(s);provider_fake=NULL;
}

static void test_voice_key_none(void){
    fake_t f={0};input_commands=0;vk_usb_service_t*s=make(&f);
    vk_usb_input_handler_registration_t registration={on_input_command,NULL};
    assert(vk_usb_service_register_input_handler(s,&registration)==ESP_OK);
    assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);
    frame(&f,"{\"event\":\"voice_key\",\"key\":\"none\"}");all(s,&f);
    assert(input_commands==1&&last_input_command.kind==VK_USB_INPUT_COMMAND_VOICE_KEY&&last_input_command.key==VK_USB_KEY_NONE);
    f.output_count=0;assert(vk_usb_service_send_input_state_for_epoch(s,vk_usb_service_epoch(s),VK_USB_INPUT_MODE_HOLD_TO_TALK,VK_USB_KEY_NONE)==ESP_OK);
    assert(contains(&f,"\"voice_key\":\"none\""));
    assert(vk_usb_service_stop(s)==ESP_OK);free(s);
}

static void test_zero_upload_management(void)
{
    const char *sha="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    fake_t f={0};commands=chunks=0;vk_usb_service_t *service=make(&f);register_asset(service);
    provider_snapshot.assets.upload_max_bytes=0U;
    assert(vk_usb_service_start(service)==ESP_OK);epoch(service,&f);authorize(service,&f);
    char command[256];
    snprintf(command,sizeof(command),"{\"event\":\"vk_asset_begin\",\"transfer_id\":9,\"sha256\":\"%s\",\"total_bytes\":1,\"kind\":\"image\"}",sha);
    frame(&f,command);all(service,&f);assert(commands==0);
    reset_in(&f);frame(&f,"{\"event\":\"vk_asset_query\",\"transfer_id\":9}");all(service,&f);
    reset_in(&f);frame(&f,"{\"event\":\"vk_asset_list\",\"snapshot_id\":0,\"cursor\":0,\"limit\":1}");all(service,&f);
    snprintf(command,sizeof(command),"{\"event\":\"vk_asset_delete\",\"sha256\":\"%s\",\"expected_revision\":0}",sha);
    reset_in(&f);frame(&f,command);all(service,&f);assert(commands==2&&last_cmd.kind==VK_USB_ASSET_DELETE);
    uint8_t chunk[9]={9,0,0,0,0,0,0,0,1};reset_in(&f);frame_t(&f,VK_USB_FRAME_TYPE_ASSET_CHUNK,chunk,sizeof(chunk));all(service,&f);assert(chunks==0);
    assert(vk_usb_service_stop(service)==ESP_OK);free(service);
}

static void test_active_asset_transfer(void)
{
    const char *sha="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    fake_t f={0};commands=chunks=0;command_result=chunk_result=ESP_OK;vk_usb_service_t*s=make(&f);register_asset(s);
    assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);authorize(s,&f);char json[256];
    snprintf(json,sizeof(json),"{\"event\":\"vk_asset_begin\",\"transfer_id\":9,\"sha256\":\"%s\",\"total_bytes\":5,\"kind\":\"image\"}",sha);
    frame(&f,json);all(s,&f);assert(commands==1&&contains(&f,"vk_asset_ready"));
    reset_in(&f);f.output_count=0;frame(&f,json);all(s,&f);assert(commands==1&&contains(&f,"vk_asset_ready"));
    uint8_t chunk1[]={9,0,0,0,0,0,0,0,1,2,3,4};reset_in(&f);f.output_count=0;frame_t(&f,VK_USB_FRAME_TYPE_ASSET_CHUNK,chunk1,sizeof(chunk1));all(s,&f);assert(chunks==1&&last_chunk.expected_epoch!=0U&&last_chunk.snapshot_generation!=0U&&last_chunk.offset==0&&last_chunk.payload_length==4&&contains(&f,"\"next_offset\":4"));
    reset_in(&f);f.output_count=0;frame_t(&f,VK_USB_FRAME_TYPE_ASSET_CHUNK,chunk1,sizeof(chunk1));all(s,&f);assert(chunks==1&&contains(&f,"bad_offset")&&contains(&f,"\"next_offset\":4"));
    uint8_t final[]={9,0,0,0,4,0,0,0,5};chunk_result=ESP_FAIL;reset_in(&f);f.output_count=0;frame_t(&f,VK_USB_FRAME_TYPE_ASSET_CHUNK,final,sizeof(final));all(s,&f);assert(chunks==2&&contains(&f,"write_failed")&&contains(&f,"phase=chunk;esp_err=0xffffffff")&&contains(&f,"\"next_offset\":4"));
    chunk_result=ESP_OK;reset_in(&f);f.output_count=0;frame_t(&f,VK_USB_FRAME_TYPE_ASSET_CHUNK,final,sizeof(final));all(s,&f);assert(chunks==3&&contains(&f,"\"next_offset\":5"));
    snprintf(json,sizeof(json),"{\"event\":\"vk_asset_end\",\"transfer_id\":9,\"sha256\":\"%s\",\"total_bytes\":5,\"kind\":\"image\"}",sha);command_result=ESP_FAIL;reset_in(&f);f.output_count=0;frame(&f,json);all(s,&f);assert(commands==2&&contains(&f,"write_failed")&&contains(&f,"phase=end;esp_err=0xffffffff"));command_result=ESP_OK;reset_in(&f);f.output_count=0;frame(&f,json);all(s,&f);assert(commands==3&&contains(&f,"vk_asset_stored"));
    reset_in(&f);f.output_count=0;frame_t(&f,VK_USB_FRAME_TYPE_ASSET_CHUNK,final,sizeof(final));all(s,&f);assert(chunks==3&&contains(&f,"unavailable"));
    reset_in(&f);f.output_count=0;frame(&f,"{\"event\":\"vk_asset_abort\",\"transfer_id\":9}");all(s,&f);assert(commands==3&&contains(&f,"vk_asset_aborted"));
    assert(vk_usb_service_stop(s)==ESP_OK);free(s);
}

static void test_wire(void){fake_t f={0};commands=chunks=0;vk_usb_service_t*s=make(&f);register_asset(s);assert(vk_usb_service_register_update_handler(s,NULL)==ESP_ERR_INVALID_ARG);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);authorize(s,&f);const char*valid[]={"{\"event\":\"vk_asset_begin\",\"transfer_id\":1,\"sha256\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"total_bytes\":9,\"kind\":\"image\"}","{\"event\":\"vk_asset_query\",\"transfer_id\":1}","{\"event\":\"vk_asset_end\",\"transfer_id\":1,\"sha256\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"total_bytes\":9,\"kind\":\"animation\"}","{\"event\":\"vk_asset_abort\",\"transfer_id\":1}","{\"event\":\"vk_asset_list\",\"snapshot_id\":1,\"cursor\":4294967295,\"limit\":64}","{\"event\":\"vk_asset_delete\",\"sha256\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"expected_revision\":0}"};for(size_t i=0;i<6;++i){reset_in(&f);frame(&f,valid[i]);all(s,&f);}assert(commands==4&&last_cmd.kind==VK_USB_ASSET_DELETE);const char*invalid[]={"{\"event\":\"vk_asset_query\",\"transfer_id\":0}","{\"event\":\"vk_asset_list\",\"cursor\":0,\"limit\":65}","{\"event\":\"vk_asset_query\",\"transfer_id\":1,\"extra\":0}","{\"event\":\"vk_asset_begin\",\"transfer_id\":4294967296,\"sha256\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"total_bytes\":1,\"kind\":\"image\"}","{\"event\":\"vk_asset_begin\",\"transfer_id\":1,\"sha256\":\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\",\"total_bytes\":1,\"kind\":\"image\"}","{\"event\":\"vk_update_begin\",\"transfer_id\":1,\"size\":1,\"sha256\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"}" };for(size_t i=0;i<6;++i){reset_in(&f);frame(&f,invalid[i]);all(s,&f);}assert(commands==4);uint8_t b[13]={1,0,0,0,0,0,0,0,1,2,3,4,5};for(size_t n=8;n<=13;++n){reset_in(&f);frame_t(&f,0x40,b,n);all(s,&f);}assert(chunks==0);reset_in(&f);frame_t(&f,0x41,b,9);all(s,&f);assert(chunks==0);assert(vk_usb_service_stop(s)==ESP_OK);free(s);}

typedef struct{pthread_mutex_t mutex;pthread_cond_t condition;bool reached,released;} barrier_t;static void before_commit(void*c){barrier_t*b=c;assert(pthread_mutex_lock(&b->mutex)==0);b->reached=true;assert(pthread_cond_broadcast(&b->condition)==0);while(!b->released)assert(pthread_cond_wait(&b->condition,&b->mutex)==0);assert(pthread_mutex_unlock(&b->mutex)==0);}typedef struct{vk_usb_service_t*s;esp_err_t result;} one_poll_t;static void*poll_once(void*c){one_poll_t*x=c;x->result=vk_usb_service_poll(x->s);return NULL;}static void wait_barrier(barrier_t*b){assert(pthread_mutex_lock(&b->mutex)==0);while(!b->reached)assert(pthread_cond_wait(&b->condition,&b->mutex)==0);assert(pthread_mutex_unlock(&b->mutex)==0);}static void release_barrier(barrier_t*b){assert(pthread_mutex_lock(&b->mutex)==0);b->released=true;assert(pthread_cond_broadcast(&b->condition)==0);assert(pthread_mutex_unlock(&b->mutex)==0);}
static void test_dequeue_overflow_priority(void){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);f.output_count=0;vk_usb_button_event_t button={.kind=VK_USB_BUTTON_CLICK,.key=VK_USB_KEY_K1};for(unsigned i=0;i<VK_USB_TYPED_TX_QUEUE_CAPACITY;i++)assert(vk_usb_service_send_button(s,&button)==ESP_OK);barrier_t b={.mutex=PTHREAD_MUTEX_INITIALIZER,.condition=PTHREAD_COND_INITIALIZER};vk_usb_service_set_before_tx_commit_hook_for_test(s,before_commit,&b);one_poll_t p={.s=s};pthread_t thread;assert(pthread_create(&thread,NULL,poll_once,&p)==0);wait_barrier(&b);assert(vk_usb_service_send_button(s,&button)==ESP_OK);assert(vk_usb_service_send_button(s,&button)==ESP_ERR_NO_MEM);release_barrier(&b);assert(pthread_join(thread,NULL)==0);assert(p.result==ESP_OK);assert(contains(&f,"control_queue_overflow"));assert(!contains(&f,"button_click"));vk_usb_service_set_before_tx_commit_hook_for_test(s,NULL,NULL);assert(vk_usb_service_stop(s)==ESP_OK);free(s);}
static size_t decode_frame(const uint8_t *bytes,size_t count,size_t offset,uint8_t *type,const uint8_t **body,size_t *length){assert(offset+4U<=count);assert(bytes[offset]==VK_USB_PROTOCOL_VERSION);*type=bytes[offset+1];*length=(size_t)bytes[offset+2]|((size_t)bytes[offset+3]<<8U);assert(offset+4U+*length<=count);*body=bytes+offset+4U;return offset+4U+*length;}
static void assert_json_frame(fake_t*f,const char*expected){uint8_t type;const uint8_t*body;size_t length;size_t end=decode_frame(f->output,f->output_count,0,&type,&body,&length);assert(type==VK_USB_FRAME_TYPE_JSON);assert(length==strlen(expected));assert(memcmp(body,expected,length)==0);assert(end==f->output_count);}
static void init_barrier(barrier_t*b){assert(pthread_mutex_init(&b->mutex,NULL)==0);assert(pthread_cond_init(&b->condition,NULL)==0);b->reached=false;b->released=false;}
static void test_audio_dequeue_overflow_priority(void){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);f.output_count=0;uint8_t payload=0x5a;vk_usb_audio_frame_t a={.session_id=7,.sequence=11,.flags=1,.payload=&payload,.payload_length=1};for(unsigned i=0;i<VK_USB_TYPED_TX_QUEUE_CAPACITY;i++)assert(vk_usb_service_send_audio(s,&a)==ESP_OK);barrier_t b;init_barrier(&b);vk_usb_service_set_before_tx_commit_hook_for_test(s,before_commit,&b);one_poll_t p={.s=s};pthread_t thread;assert(pthread_create(&thread,NULL,poll_once,&p)==0);wait_barrier(&b);assert(vk_usb_service_send_audio(s,&a)==ESP_OK);assert(vk_usb_service_send_audio(s,&a)==ESP_ERR_NO_MEM);vk_usb_audio_frame_t other=a;other.session_id=8;assert(vk_usb_service_send_audio(s,&other)==ESP_ERR_INVALID_STATE);release_barrier(&b);assert(pthread_join(thread,NULL)==0);assert(p.result==ESP_OK);assert_json_frame(&f,"{\"event\":\"vk_error\",\"operation\":\"audio\",\"code\":\"audio_queue_overflow\",\"session_id\":7}");poll(s);assert(vk_usb_service_tx_queue_count_for_test(s)==0);assert(f.output_count>0);vk_usb_service_set_before_tx_commit_hook_for_test(s,NULL,NULL);assert(vk_usb_service_stop(s)==ESP_OK);free(s);}
static void test_terminal_write_failures(void){for(unsigned partial=0;partial<2;++partial){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);f.output_count=0;vk_usb_button_event_t button={.kind=VK_USB_BUTTON_CLICK,.key=VK_USB_KEY_K1};for(unsigned i=0;i<VK_USB_TYPED_TX_QUEUE_CAPACITY;i++)assert(vk_usb_service_send_button(s,&button)==ESP_OK);assert(vk_usb_service_send_button(s,&button)==ESP_ERR_NO_MEM);if(partial==0)f.write_mode=-1;else{f.write_limit=5;f.write_fail_after=2;}assert(vk_usb_service_poll(s)==ESP_FAIL);if(partial==0)assert(f.output_count==0);else{assert(f.output_count==5);assert(f.output[0]==1&&f.output[1]==VK_USB_FRAME_TYPE_JSON);size_t declared=(size_t)f.output[2]|((size_t)f.output[3]<<8U);assert(f.output_count<declared+4U);}f.write_mode=0;f.write_fail_after=0;assert(vk_usb_service_stop(s)==ESP_OK);assert(f.uninstall_count==1);free(s);}}
static void test_barrier_expiry_epoch_and_stop(void){
    {fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);f.output_count=0;vk_usb_button_event_t x={.kind=VK_USB_BUTTON_CLICK,.key=VK_USB_KEY_K2};assert(vk_usb_service_send_button(s,&x)==ESP_OK);barrier_t b;init_barrier(&b);vk_usb_service_set_before_tx_commit_hook_for_test(s,before_commit,&b);one_poll_t p={.s=s};pthread_t t;assert(pthread_create(&t,NULL,poll_once,&p)==0);wait_barrier(&b);atomic_store(&f.now_ms,VK_USB_LEASE_MS);release_barrier(&b);assert(pthread_join(t,NULL)==0);assert(p.result==ESP_OK);assert(f.output_count==0);assert(!vk_usb_service_has_epoch(s));vk_usb_service_set_before_tx_commit_hook_for_test(s,NULL,NULL);assert(vk_usb_service_stop(s)==ESP_OK);free(s);}
    {fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);uint32_t old=vk_usb_service_epoch(s);reset_in(&f);f.output_count=0;vk_usb_button_event_t x={.kind=VK_USB_BUTTON_CLICK,.key=VK_USB_KEY_K3};assert(vk_usb_service_send_button(s,&x)==ESP_OK);barrier_t b;init_barrier(&b);vk_usb_service_set_before_tx_commit_hook_for_test(s,before_commit,&b);one_poll_t p={.s=s};pthread_t t;assert(pthread_create(&t,NULL,poll_once,&p)==0);wait_barrier(&b);const char*j="{\"event\":\"transport\",\"kind\":\"usb\"}";uint8_t raw[64]={1,VK_USB_FRAME_TYPE_JSON,(uint8_t)strlen(j),0};memcpy(raw+4,j,strlen(j));assert(vk_usb_service_consume_for_test(s,raw,strlen(j)+4)==ESP_OK);assert(vk_usb_service_epoch(s)==old+1U);release_barrier(&b);assert(pthread_join(t,NULL)==0);assert(p.result==ESP_OK);assert(f.output_count==0);assert(vk_usb_service_tx_queue_count_for_test(s)==0);vk_usb_service_set_before_tx_commit_hook_for_test(s,NULL,NULL);assert(vk_usb_service_stop(s)==ESP_OK);free(s);}
    {fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);f.output_count=0;vk_usb_button_event_t x={.kind=VK_USB_BUTTON_CLICK,.key=VK_USB_KEY_K4};assert(vk_usb_service_send_button(s,&x)==ESP_OK);barrier_t b;init_barrier(&b);vk_usb_service_set_before_tx_commit_hook_for_test(s,before_commit,&b);one_poll_t p={.s=s};pthread_t t;assert(pthread_create(&t,NULL,poll_once,&p)==0);wait_barrier(&b);assert(vk_usb_service_stop(s)==ESP_ERR_INVALID_STATE);assert(f.uninstall_count==0);release_barrier(&b);assert(pthread_join(t,NULL)==0);assert(p.result==ESP_ERR_INVALID_STATE);assert(f.output_count==0);assert(vk_usb_service_stop(s)==ESP_OK);assert(f.uninstall_count==1);vk_usb_service_set_before_tx_commit_hook_for_test(s,NULL,NULL);free(s);}
}
static void test_pending_audio_terminal_rejects_other_session(void){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);uint8_t payload=1;vk_usb_audio_frame_t a={.session_id=7,.payload=&payload,.payload_length=1};for(unsigned i=0;i<VK_USB_TYPED_TX_QUEUE_CAPACITY;i++)assert(vk_usb_service_send_audio(s,&a)==ESP_OK);assert(vk_usb_service_send_audio(s,&a)==ESP_ERR_NO_MEM);vk_usb_audio_frame_t other=a;other.session_id=8;assert(vk_usb_service_send_audio(s,&other)==ESP_ERR_INVALID_STATE);f.output_count=0;poll(s);assert(contains(&f,"\"session_id\":7"));assert(!contains(&f,"\"session_id\":8"));assert(vk_usb_service_stop(s)==ESP_OK);free(s);}
static void test_queue(void){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);for(unsigned i=0;i<VK_USB_TYPED_TX_QUEUE_CAPACITY;i++){vk_usb_button_event_t b={.kind=VK_USB_BUTTON_CLICK,.key=(vk_usb_key_t)(i%4)};assert(vk_usb_service_send_button(s,&b)==ESP_OK);}vk_usb_button_event_t overflow={.kind=VK_USB_BUTTON_CLICK,.key=VK_USB_KEY_K1};assert(vk_usb_service_send_button(s,&overflow)==ESP_ERR_NO_MEM);assert(!vk_usb_service_has_epoch(s));assert(vk_usb_service_tx_queue_count_for_test(s)==0);poll(s);assert(contains(&f,"\"operation\":\"session\",\"code\":\"control_queue_overflow\""));epoch(s,&f);reset_in(&f);f.output_count=0;uint8_t source[]={1,2,3};vk_usb_audio_frame_t a={7,2,1,source,3};for(unsigned i=0;i<VK_USB_TYPED_TX_QUEUE_CAPACITY;i++)assert(vk_usb_service_send_audio(s,&a)==ESP_OK);assert(vk_usb_service_send_audio(s,&a)==ESP_ERR_NO_MEM);assert(vk_usb_service_tx_queue_count_for_test(s)==0);poll(s);assert(contains(&f,"\"operation\":\"audio\",\"code\":\"audio_queue_overflow\",\"session_id\":7"));assert(vk_usb_service_send_audio(s,&a)==ESP_ERR_INVALID_STATE);epoch(s,&f);assert(vk_usb_service_send_audio(s,&a)==ESP_OK);source[0]=9;poll(s);assert(f.output[f.output_count-3]==1);assert(f.locks==0);assert(vk_usb_service_stop(s)==ESP_OK);free(s);}

static void test_every_split_and_recovery(void){uint8_t body[4092];memset(body,' ',sizeof(body));memcpy(body,"{\"event\":\"x\"}",13);for(size_t split=1;split<=4096;++split){fake_t f={.read_limit=split};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);frame_t(&f,0x10,body,sizeof(body));frame(&f,"{\"event\":\"transport\",\"kind\":\"usb\"}");all(s,&f);assert(vk_usb_service_has_epoch(s));assert(vk_usb_service_stop(s)==ESP_OK);free(s);}const char*cap="{\"event\":\"vk_capabilities\",\"protocol\":1,\"display\":{\"width\":428,\"height\":142,\"format\":\"rgb565\"},\"features\":{}}";for(size_t split=1;split<=strlen(cap)+4;++split){fake_t f={.read_limit=split};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);frame(&f,"{\"event\":\"get_device_info\"}");all(s,&f);assert(contains(&f,cap));assert(vk_usb_service_stop(s)==ESP_OK);free(s);}fake_t f={.read_limit=17};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);for(size_t i=0;i<6000;i++)f.input[f.input_count++]=0x55;frame(&f,"{\"event\":\"transport\",\"kind\":\"usb\"}");all(s,&f);assert(vk_usb_service_has_epoch(s));assert(vk_usb_service_stop(s)==ESP_OK);free(s);}

typedef struct{vk_usb_service_t*s;atomic_bool*run;} concurrent_t;static void*concurrent_poll(void*c){concurrent_t*x=c;while(atomic_load(x->run)){esp_err_t e=vk_usb_service_poll(x->s);if(e==ESP_ERR_INVALID_STATE)break;assert(e==ESP_OK);}return NULL;}static void*concurrent_produce(void*c){concurrent_t*x=c;uint32_t n=0;while(atomic_load(x->run)){vk_usb_button_event_t b={.kind=VK_USB_BUTTON_CLICK,.key=(vk_usb_key_t)(n++%4)};esp_err_t e=vk_usb_service_send_button(x->s,&b);assert(e==ESP_OK||e==ESP_ERR_NO_MEM||e==ESP_ERR_INVALID_STATE);}return NULL;}static void test_concurrent_owner_expiry_stop(void){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);atomic_bool run=true;concurrent_t c={s,&run};pthread_t consumer,producers[3];assert(pthread_create(&consumer,NULL,concurrent_poll,&c)==0);for(size_t i=0;i<3;i++)assert(pthread_create(&producers[i],NULL,concurrent_produce,&c)==0);for(size_t i=0;i<10000;i++){(void)vk_usb_service_epoch(s);}atomic_store(&f.now_ms,VK_USB_LEASE_MS);atomic_store(&run,false);assert(pthread_join(consumer,NULL)==0);assert(vk_usb_service_stop(s)==ESP_OK);for(size_t i=0;i<3;i++)assert(pthread_join(producers[i],NULL)==0);assert(f.locks==0);free(s);}

static void test_update_disabled(void){
    update_commands=update_chunks=0;tuple_available=true;fake_t f={0};
    vk_usb_service_t*s=make_policy(&f,true);register_update_rejected(s);
    assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);
    frame(&f,"{\"event\":\"vk_update_query\",\"transfer_id\":1}");all(s,&f);
    uint8_t chunk[9]={1,0,0,0,0,0,0,0,1};reset_in(&f);frame_t(&f,VK_USB_FRAME_TYPE_UPDATE_CHUNK,chunk,sizeof(chunk));all(s,&f);
    assert(update_commands==0&&update_chunks==0);assert(vk_usb_service_stop(s)==ESP_OK);free(s);
}

static void test_exact_typed_boundaries(void){
    const char*sha="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    fake_t f={0};commands=chunks=0;vk_usb_service_t*s=make(&f);register_asset(s);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);authorize(s,&f);
    char command[256];snprintf(command,sizeof(command),"{\"event\":\"vk_asset_begin\",\"transfer_id\":9,\"sha256\":\"%s\",\"total_bytes\":1000,\"kind\":\"image\"}",sha);reset_in(&f);frame(&f,command);all(s,&f);assert(commands==1);assert(last_cmd.kind==VK_USB_ASSET_BEGIN&&last_cmd.transfer_id==9&&last_cmd.total_bytes==1000&&strcmp(last_cmd.sha256,sha)==0&&strcmp(last_cmd.asset_kind,"image")==0);
    snprintf(command,sizeof(command),"{\"event\":\"vk_asset_begin\",\"transfer_id\":9,\"sha256\":\"%s\",\"total_bytes\":1001,\"kind\":\"image\"}",sha);reset_in(&f);frame(&f,command);all(s,&f);assert(commands==1);
    const size_t payloads[]={0,1,4,5};for(size_t ci=0;ci<4;++ci){uint8_t body[13]={9,0,0,0,0x78,0x56,0x34,0x12,0xaa,0xbb,0xcc,0xdd,0xee};int before=chunks;reset_in(&f);frame_t(&f,VK_USB_FRAME_TYPE_ASSET_CHUNK,body,8+payloads[ci]);all(s,&f);assert(chunks==before);}
    uint8_t zero[9]={0};zero[8]=1;int before=chunks;reset_in(&f);frame_t(&f,VK_USB_FRAME_TYPE_ASSET_CHUNK,zero,sizeof(zero));all(s,&f);assert(chunks==before);reset_in(&f);frame_t(&f,VK_USB_FRAME_TYPE_UPDATE_CHUNK,(uint8_t[]){9,0,0,0,0,0,0,0,1},9);all(s,&f);assert(chunks==before);assert(vk_usb_service_stop(s)==ESP_OK);free(s);

    fake_t u={0};update_commands=update_chunks=0;s=make_policy(&u,true);register_update_rejected(s);
    assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&u);
    reset_in(&u);frame(&u,"{\"event\":\"vk_update_query\",\"transfer_id\":7}");all(s,&u);
    uint8_t update_body[9]={7,0,0,0,0,0,0,0,1};reset_in(&u);frame_t(&u,VK_USB_FRAME_TYPE_UPDATE_CHUNK,update_body,sizeof(update_body));all(s,&u);
    assert(update_commands==0&&update_chunks==0);assert(vk_usb_service_stop(s)==ESP_OK);free(s);
}
static void test_exact_fifo_partial_write_order(void){fake_t f={.write_limit=3};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);reset_in(&f);f.output_count=0;vk_usb_button_event_t buttons[]={{.kind=VK_USB_BUTTON_DOWN,.key=VK_USB_KEY_K1,.has_session_id=true,.session_id=10},{.kind=VK_USB_BUTTON_UP,.key=VK_USB_KEY_K2,.has_duration_ms=true,.duration_ms=20},{.kind=VK_USB_BUTTON_CLICK,.key=VK_USB_KEY_K4,.has_session_id=true,.session_id=30,.has_duration_ms=true,.duration_ms=40}};const char*json[]={"{\"event\":\"button_down\",\"button\":\"k1\",\"session_id\":10}","{\"event\":\"button_up\",\"button\":\"k2\",\"duration_ms\":20}","{\"event\":\"button_click\",\"button\":\"k4\",\"session_id\":30,\"duration_ms\":40}"};for(size_t i=0;i<3;++i)assert(vk_usb_service_send_button(s,&buttons[i])==ESP_OK);uint8_t payload[]={0x11,0x22};vk_usb_audio_frame_t audio={.session_id=50,.sequence=60,.flags=3,.payload=payload,.payload_length=2};assert(vk_usb_service_send_audio(s,&audio)==ESP_OK);for(size_t i=0;i<4;++i)poll(s);size_t offset=0;for(size_t i=0;i<3;++i){uint8_t type;const uint8_t*body;size_t length;offset=decode_frame(f.output,f.output_count,offset,&type,&body,&length);assert(type==VK_USB_FRAME_TYPE_JSON&&length==strlen(json[i])&&memcmp(body,json[i],length)==0);}assert(offset+18U==f.output_count);const uint8_t*audio_bytes=f.output+offset;assert(audio_bytes[0]==VK_USB_PROTOCOL_VERSION&&audio_bytes[1]==VK_USB_FRAME_TYPE_AUDIO&&audio_bytes[2]==0x10&&audio_bytes[3]==0);assert(audio_bytes[4]==50&&audio_bytes[8]==60&&audio_bytes[12]==3&&audio_bytes[14]==2&&audio_bytes[15]==0&&audio_bytes[16]==0x11&&audio_bytes[17]==0x22);offset+=18U;assert(offset==f.output_count);assert(vk_usb_service_stop(s)==ESP_OK);free(s);}
static void test_hostile_declared_length_progress_corpus(void){const char*t="{\"event\":\"transport\",\"kind\":\"usb\"}";uint8_t valid[64]={1,0x10,(uint8_t)strlen(t),0};memcpy(valid+4,t,strlen(t));const uint16_t lengths[]={0,1,255,4092,4093,4095,65535};for(size_t li=0;li<sizeof(lengths)/sizeof(*lengths);++li){for(size_t prefix=0;prefix<32;++prefix){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);uint8_t hostile[96];memset(hostile,0x55,sizeof(hostile));for(size_t i=0;i<prefix;++i)hostile[i]=(uint8_t)(i%3==0?1:0x55);hostile[prefix]=1;hostile[prefix+1]=0x10;hostile[prefix+2]=(uint8_t)lengths[li];hostile[prefix+3]=(uint8_t)(lengths[li]>>8);size_t n=prefix+4U;if(lengths[li]<=8U){memset(hostile+n,0x55,lengths[li]);n+=lengths[li];}size_t bytes0=vk_usb_service_consume_bytes_for_test(s),steps0=vk_usb_service_parser_steps_for_test(s);assert(vk_usb_service_consume_for_test(s,hostile,n)==ESP_OK);size_t bytes1=vk_usb_service_consume_bytes_for_test(s),steps1=vk_usb_service_parser_steps_for_test(s);assert(bytes1-bytes0==n);assert(steps1>=steps0&&steps1-steps0<=n+4U);assert(vk_usb_service_consume_for_test(s,valid,strlen(t)+4)==ESP_OK);size_t bytes2=vk_usb_service_consume_bytes_for_test(s),steps2=vk_usb_service_parser_steps_for_test(s);assert(bytes2-bytes1==strlen(t)+4U);assert(steps2>=steps1&&steps2-steps1<=strlen(t)+8U);if(lengths[li]>VK_USB_MAX_JSON_BYTES||lengths[li]<=8U)assert(vk_usb_service_has_epoch(s));assert(vk_usb_service_stop(s)==ESP_OK);free(s);}}}
static void test_hostile_saturation_fragment_layouts(void){const char*t="{\"event\":\"transport\",\"kind\":\"usb\"}";uint8_t valid[64]={1,VK_USB_FRAME_TYPE_JSON,(uint8_t)strlen(t),0};memcpy(valid+4,t,strlen(t));const uint16_t lengths[]={1,255,4092,4093,65535};const size_t fills[]={VK_USB_MAX_FRAME_BYTES-3U,VK_USB_MAX_FRAME_BYTES,VK_USB_MAX_FRAME_BYTES+17U};const size_t fragments[]={1,17,257};for(size_t li=0;li<5;++li)for(size_t fi=0;fi<3;++fi)for(size_t gi=0;gi<3;++gi){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);size_t total=4U+fills[fi];uint8_t*hostile=malloc(total);assert(hostile);memset(hostile+4,0x55,fills[fi]);hostile[0]=1;hostile[1]=VK_USB_FRAME_TYPE_JSON;hostile[2]=(uint8_t)lengths[li];hostile[3]=(uint8_t)(lengths[li]>>8U);size_t offset=0,previous_bytes=0,previous_steps=0;while(offset<total){size_t amount=fragments[gi];if(amount>total-offset)amount=total-offset;assert(vk_usb_service_consume_for_test(s,hostile+offset,amount)==ESP_OK);size_t current_bytes=vk_usb_service_consume_bytes_for_test(s),current_steps=vk_usb_service_parser_steps_for_test(s);assert(current_bytes==previous_bytes+amount);assert(current_steps>=previous_steps&&current_steps-previous_steps<=amount+4U);previous_bytes=current_bytes;previous_steps=current_steps;offset+=amount;}free(hostile);assert(vk_usb_service_consume_for_test(s,valid,strlen(t)+4U)==ESP_OK);assert(vk_usb_service_consume_bytes_for_test(s)==previous_bytes+strlen(t)+4U);assert(vk_usb_service_parser_steps_for_test(s)>=previous_steps);assert(vk_usb_service_parser_steps_for_test(s)-previous_steps<=strlen(t)+8U);assert(vk_usb_service_has_epoch(s));assert(vk_usb_service_stop(s)==ESP_OK);free(s);}}
static void test_exact_splits_and_declared_progress(void){uint8_t body[4092];memset(body,' ',sizeof(body));memcpy(body,"{\"event\":\"x\"}",13);uint8_t complete[4096]={1,0x10,0xfc,0x0f};memcpy(complete+4,body,sizeof(body));for(size_t split=0;split<=sizeof(complete);split++){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);assert(vk_usb_service_consume_for_test(s,complete,split)==ESP_OK);assert(vk_usb_service_consume_for_test(s,complete+split,sizeof(complete)-split)==ESP_OK);const char*t="{\"event\":\"transport\",\"kind\":\"usb\"}";uint8_t valid[64]={1,0x10,(uint8_t)strlen(t),0};memcpy(valid+4,t,strlen(t));assert(vk_usb_service_consume_for_test(s,valid,strlen(t)+4)==ESP_OK);assert(vk_usb_service_has_epoch(s));assert(vk_usb_service_stop(s)==ESP_OK);free(s);}fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);uint8_t oversized[4097];memset(oversized,0x55,sizeof(oversized));oversized[0]=1;oversized[1]=0x10;oversized[2]=0xfd;oversized[3]=0x0f;assert(vk_usb_service_consume_for_test(s,oversized,sizeof(oversized))==ESP_OK);const char*t="{\"event\":\"transport\",\"kind\":\"usb\"}";uint8_t valid[64]={1,0x10,(uint8_t)strlen(t),0};memcpy(valid+4,t,strlen(t));assert(vk_usb_service_consume_for_test(s,valid,strlen(t)+4)==ESP_OK);assert(vk_usb_service_has_epoch(s));assert(vk_usb_service_stop(s)==ESP_OK);free(s);}

typedef struct { vk_usb_input_lifecycle_request_t request; vk_usb_input_lifecycle_sink_t sink; fake_t *transport; bool auto_ack; vk_usb_input_lifecycle_ack_result_t result; int calls; } lifecycle_probe_t;
static vk_usb_input_lifecycle_begin_result_t lifecycle_begin(void *context,const vk_usb_input_lifecycle_request_t *request,const vk_usb_input_lifecycle_sink_t *sink){lifecycle_probe_t*p=context;assert(p->transport==NULL||p->transport->locks==0);p->request=*request;p->sink=*sink;++p->calls;if(p->auto_ack){vk_usb_input_lifecycle_ack_t ack={request->token,request->lifecycle_generation,p->result};(void)sink->publish(sink->context,&ack);}return VK_USB_INPUT_LIFECYCLE_ACCEPTED;}
static void test_input_lifecycle_boundaries(void){
    fake_t f={0};vk_usb_service_t*s=make(&f);lifecycle_probe_t p={.transport=&f,.auto_ack=true,.result=VK_USB_INPUT_LIFECYCLE_QUIESCENT};vk_usb_input_lifecycle_registration_t r={lifecycle_begin,&p};assert(vk_usb_service_register_input_lifecycle(s,&r)==ESP_OK);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);assert(p.calls==1&&p.request.old_epoch==0U&&p.request.proposed_epoch!=0U);uint32_t epoch1=vk_usb_service_epoch(s);
    p.auto_ack=false;reset_in(&f);f.output_count=0;frame(&f,"{\"event\":\"transport\",\"kind\":\"usb\"}");assert(vk_usb_service_poll(s)==ESP_OK);assert(!vk_usb_service_has_epoch(s));assert(f.output_count==0);reset_in(&f);frame(&f,"{\"event\":\"get_device_info\"}");assert(vk_usb_service_poll(s)==ESP_OK);assert(f.input_offset==0&&f.output_count==0);vk_usb_input_lifecycle_ack_t wrong={p.request.token+1U,p.request.lifecycle_generation,VK_USB_INPUT_LIFECYCLE_QUIESCENT};assert(!p.sink.publish(p.sink.context,&wrong));atomic_store(&f.now_ms,3250U-1U);vk_usb_input_lifecycle_ack_t good={p.request.token,p.request.lifecycle_generation,VK_USB_INPUT_LIFECYCLE_QUIESCENT};assert(p.sink.publish(p.sink.context,&good));assert(!p.sink.publish(p.sink.context,&good));assert(vk_usb_service_process_lifecycle(s)==ESP_OK);assert(vk_usb_service_has_epoch(s)&&vk_usb_service_epoch(s)!=epoch1);all(s,&f);
    uint32_t epoch2=vk_usb_service_epoch(s);p.auto_ack=false;reset_in(&f);atomic_store(&f.now_ms,10000U);frame(&f,"{\"event\":\"transport\",\"kind\":\"usb\"}");assert(vk_usb_service_poll(s)==ESP_OK);assert(!vk_usb_service_has_epoch(s));assert(p.request.absolute_deadline_ms==10000U+1500U+1500U+250U);atomic_store(&f.now_ms,10000U+3250U);good=(vk_usb_input_lifecycle_ack_t){p.request.token,p.request.lifecycle_generation,VK_USB_INPUT_LIFECYCLE_QUIESCENT};assert(!p.sink.publish(p.sink.context,&good));assert(vk_usb_service_process_lifecycle(s)==ESP_ERR_TIMEOUT);assert(vk_usb_service_is_tainted(s));assert(!vk_usb_service_has_epoch(s));assert(vk_usb_service_epoch(s)==epoch2);free(s);
    fake_t late={0};s=make(&late);lifecycle_probe_t q={.transport=&late,.auto_ack=false,.result=VK_USB_INPUT_LIFECYCLE_QUIESCENT};r=(vk_usb_input_lifecycle_registration_t){lifecycle_begin,&q};assert(vk_usb_service_register_input_lifecycle(s,&r)==ESP_OK);assert(vk_usb_service_start(s)==ESP_OK);frame(&late,"{\"event\":\"transport\",\"kind\":\"usb\"}");assert(vk_usb_service_poll(s)==ESP_OK);assert(!vk_usb_service_has_epoch(s));atomic_store(&late.now_ms,3251U);good=(vk_usb_input_lifecycle_ack_t){q.request.token,q.request.lifecycle_generation,VK_USB_INPUT_LIFECYCLE_QUIESCENT};assert(!q.sink.publish(q.sink.context,&good));assert(vk_usb_service_process_lifecycle(s)==ESP_ERR_TIMEOUT);assert(vk_usb_service_is_tainted(s));free(s);
}
static void test_lifecycle(void){fake_t f={.uninstall_fail=true};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);assert(vk_usb_service_stop(s)==ESP_FAIL);assert(vk_usb_service_start(s)==ESP_ERR_INVALID_STATE);f.uninstall_fail=false;assert(vk_usb_service_stop(s)==ESP_OK);free(s);for(int m=-1;m<=2;m++){if(m==0)continue;fake_t x={.write_mode=m};s=make(&x);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&x);reset_in(&x);frame(&x,"{\"event\":\"get_device_info\"}");assert(vk_usb_service_poll(s)==ESP_FAIL);x.write_mode=0;assert(vk_usb_service_stop(s)==ESP_OK);free(s);}}
static void test_audio_epoch_handoff(void){fake_t f={0};vk_usb_service_t*s=make(&f);assert(vk_usb_service_start(s)==ESP_OK);epoch(s,&f);uint32_t current=vk_usb_service_epoch(s);uint8_t payload=0x5a;vk_usb_audio_frame_t a={.session_id=7,.sequence=0,.flags=1,.payload=&payload,.payload_length=1};assert(current!=0U);assert(vk_usb_service_send_audio_for_epoch(s,current,&a)==ESP_OK);assert(vk_usb_service_send_audio_for_epoch(s,current+1U,&a)==ESP_ERR_INVALID_STATE);assert(vk_usb_service_send_audio_for_epoch(s,0U,&a)==ESP_ERR_INVALID_ARG);assert(vk_usb_service_stop(s)==ESP_OK);free(s);pthread_mutex_destroy(&f.mutex);}
int main(void){test_input_lifecycle_boundaries();test_provider_lifetime_stop();test_capability_provider();test_voice_key_none();test_zero_upload_management();test_active_asset_transfer();test_audio_epoch_handoff();test_unicode();test_wire();test_exact_typed_boundaries();test_exact_fifo_partial_write_order();test_dequeue_overflow_priority();test_audio_dequeue_overflow_priority();test_terminal_write_failures();test_barrier_expiry_epoch_and_stop();test_pending_audio_terminal_rejects_other_session();test_queue();test_every_split_and_recovery();test_hostile_declared_length_progress_corpus();test_hostile_saturation_fragment_layouts();test_exact_splits_and_declared_progress();test_update_disabled();test_concurrent_owner_expiry_stop();test_lifecycle();puts("vk_usb native tests passed");}
