#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "vk_asset_store.h"
#include "vk_screen_service.h"
#include "vk_vka1.h"

#ifndef ESP_ERR_NOT_FOUND
#define ESP_ERR_NOT_FOUND 0x105
#endif
#ifndef ESP_ERR_INVALID_RESPONSE
#define ESP_ERR_INVALID_RESPONSE 0x108
#endif
#ifndef ESP_ERR_INVALID_CRC
#define ESP_ERR_INVALID_CRC 0x109
#endif

#define FILE_CAPACITY 32U
#define FILE_BYTES 8192U

typedef struct { char name[VK_ASSET_PATH_BYTES]; uint8_t data[FILE_BYTES]; size_t size; bool used; } file_t;
typedef struct { file_t files[FILE_CAPACITY]; uint64_t now_ms; } fs_t;
typedef struct { uint8_t input[32768]; size_t input_count,input_offset; uint8_t output[65536]; size_t output_count; fs_t *fs; } transport_t;
typedef struct { vk_screen_model_t model; uint16_t *pixels; size_t pixel_count; } render_root_t;
typedef struct { fs_t *fs; vk_display_t *display; void *active; unsigned creates,swaps,destroys,flushes; bool fail_create,fail_flush; } renderer_t;

static file_t *file_find(fs_t *fs,const char *name){for(size_t i=0;i<FILE_CAPACITY;i++)if(fs->files[i].used&&!strcmp(fs->files[i].name,name))return &fs->files[i];return NULL;}
static file_t *file_new(fs_t *fs,const char *name){if(file_find(fs,name))return NULL;for(size_t i=0;i<FILE_CAPACITY;i++)if(!fs->files[i].used){fs->files[i].used=true;snprintf(fs->files[i].name,sizeof(fs->files[i].name),"%s",name);return &fs->files[i];}return NULL;}
static esp_err_t mount_fs(void*c,bool format){(void)c;return format?ESP_FAIL:ESP_OK;}static esp_err_t unmount_fs(void*c){(void)c;return ESP_OK;}static esp_err_t format_fs(void*c){(void)c;return ESP_FAIL;}
static esp_err_t erased_fs(void*c,uint32_t o,uint32_t z,uint8_t h[32],bool*a){(void)c;(void)o;(void)z;memset(h,0,32);*a=false;return ESP_OK;}
static esp_err_t read_fs(void*c,const char*n,size_t o,uint8_t*b,size_t cap,size_t*got){file_t*f=file_find(c,n);if(!f)return ESP_ERR_NOT_FOUND;if(o>f->size)return ESP_ERR_INVALID_STATE;*got=f->size-o<cap?f->size-o:cap;memcpy(b,f->data+o,*got);return ESP_OK;}
static esp_err_t size_fs(void*c,const char*n,size_t*z){file_t*f=file_find(c,n);if(!f)return ESP_ERR_NOT_FOUND;*z=f->size;return ESP_OK;}
static esp_err_t new_fs(void*c,const char*n,const uint8_t*b,size_t z,bool sync){(void)sync;if(z>FILE_BYTES)return ESP_ERR_NO_MEM;file_t*f=file_new(c,n);if(!f)return ESP_ERR_INVALID_STATE;if(z)memcpy(f->data,b,z);f->size=z;return ESP_OK;}
static esp_err_t rewrite_fs(void*c,const char*n,const uint8_t*b,size_t z,bool sync){(void)sync;file_t*f=file_find(c,n);if(!f)f=file_new(c,n);if(!f||z>FILE_BYTES)return ESP_ERR_NO_MEM;if(z)memcpy(f->data,b,z);f->size=z;return ESP_OK;}
static esp_err_t append_fs(void*c,const char*n,size_t o,const uint8_t*b,size_t z,bool sync){(void)sync;file_t*f=file_find(c,n);if(!f||f->size!=o||o+z>FILE_BYTES)return ESP_ERR_INVALID_STATE;memcpy(f->data+o,b,z);f->size+=z;return ESP_OK;}
static esp_err_t truncate_fs(void*c,const char*n,size_t z,bool sync){(void)sync;file_t*f=file_find(c,n);if(!f||z>f->size)return ESP_ERR_INVALID_STATE;f->size=z;return ESP_OK;}
static esp_err_t remove_fs(void*c,const char*n){file_t*f=file_find(c,n);if(!f)return ESP_ERR_NOT_FOUND;memset(f,0,sizeof(*f));return ESP_OK;}
static esp_err_t list_fs(void*c,const char*p,char names[][VK_ASSET_PATH_BYTES],size_t cap,size_t*count){fs_t*fs=c;*count=0;for(size_t i=0;i<FILE_CAPACITY;i++)if(fs->files[i].used&&(!strcmp(p,"/")||!strncmp(fs->files[i].name,p,strlen(p)))){if(*count==cap)return ESP_ERR_NO_MEM;snprintf(names[(*count)++],VK_ASSET_PATH_BYTES,"%s",fs->files[i].name);}return ESP_OK;}
static esp_err_t free_fs(void*c,uint32_t*out){(void)c;*out=100000;return ESP_OK;}
static const vk_asset_fs_ops_t fs_ops={mount_fs,unmount_fs,format_fs,erased_fs,read_fs,size_fs,new_fs,rewrite_fs,append_fs,truncate_fs,remove_fs,list_fs,free_fs};

static void hex_sha(const uint8_t digest[32],char output[65]){static const char h[]="0123456789abcdef";for(size_t i=0;i<32;i++){output[i*2]=h[digest[i]>>4];output[i*2+1]=h[digest[i]&15];}output[64]=0;}
static bool parse_hex(const char *text,uint8_t out[32]){if(!text||strlen(text)!=64)return false;for(size_t i=0;i<32;i++){unsigned a=text[i*2]>='a'?text[i*2]-'a'+10:text[i*2]-'0',b=text[i*2+1]>='a'?text[i*2+1]-'a'+10:text[i*2+1]-'0';if(a>15||b>15)return false;out[i]=(uint8_t)((a<<4)|b);}return true;}
static esp_err_t validate_asset(void*c,const char*n,const uint8_t expected[32],uint32_t exact,vk_asset_kind_t kind){fs_t*fs=c;file_t*f=file_find(fs,n);if(!f||f->size!=exact)return ESP_ERR_INVALID_SIZE;vk_vka1_limits_t limits={.max_frames=64,.min_frame_ms=10,.max_frame_ms=60000,.max_container_bytes=4096,.max_decoded_bytes=243104};vk_vka1_info_t info;vk_vka1_result_t r=vk_vka1_validate(f->data,f->size,&limits,&info);if(r!=VK_VKA1_OK)return ESP_ERR_INVALID_RESPONSE;if(memcmp(info.sha256,expected,32))return ESP_ERR_INVALID_CRC;if((kind==VK_ASSET_KIND_IMAGE&&info.kind!=VK_VKA1_IMAGE)||(kind==VK_ASSET_KIND_ANIMATION&&info.kind!=VK_VKA1_ANIMATION))return ESP_ERR_INVALID_RESPONSE;return ESP_OK;}
static esp_err_t validate_revision(void*c,uint32_t revision,uint32_t previous,const uint8_t*a,size_t az,const uint8_t*s,size_t sz){(void)c;char needle[64];int n=snprintf(needle,sizeof(needle),"\"previous_revision\":%u,\"revision\":%u,\"schema\":1}",(unsigned)previous,(unsigned)revision);if(n<=0||az<(size_t)n||sz<(size_t)n||memcmp(a+az-(size_t)n,needle,(size_t)n)||memcmp(s+sz-(size_t)n,needle,(size_t)n))return ESP_ERR_INVALID_RESPONSE;return ESP_OK;}
static uint64_t clock_ms(void*c){return ((fs_t*)c)->now_ms;}

static esp_err_t resolve(void*c,const char*sha,vk_screen_asset_info_t*info){renderer_t*r=c;uint8_t digest[32];if(!parse_hex(sha,digest))return ESP_ERR_INVALID_ARG;char path[VK_ASSET_PATH_BYTES];snprintf(path,sizeof(path),"/assets/%s.vka",sha);file_t*f=file_find(r->fs,path);if(!f)return ESP_ERR_NOT_FOUND;vk_vka1_limits_t limits={64,10,60000,4096,243104};vk_vka1_info_t parsed;if(vk_vka1_validate(f->data,f->size,&limits,&parsed)!=VK_VKA1_OK)return ESP_ERR_INVALID_RESPONSE;uint8_t*copy=malloc(f->size);if(!copy)return ESP_ERR_NO_MEM;memcpy(copy,f->data,f->size);*info=(vk_screen_asset_info_t){parsed.kind,parsed.width,parsed.height,parsed.frame_count,parsed.decoded_bytes_per_frame,copy,f->size};return ESP_OK;}
static void release_asset(void*c,vk_screen_asset_info_t*info){(void)c;free((void*)info->container);info->container=NULL;}
static esp_err_t renderer_lock(void*c){(void)c;return ESP_OK;}static void renderer_unlock(void*c){(void)c;}
static esp_err_t create_root(void*c,const vk_screen_model_t*m,void**root){renderer_t*r=c;r->creates++;if(r->fail_create)return ESP_FAIL;render_root_t*x=calloc(1,sizeof(*x));if(!x)return ESP_ERR_NO_MEM;x->model=*m;for(uint16_t i=0;i<m->object_count;i++)if(m->objects[i].type==VK_SCREEN_OBJECT_IMAGE||m->objects[i].type==VK_SCREEN_OBJECT_PET){vk_screen_asset_info_t info={0};esp_err_t e=resolve(r,m->objects[i].sha256,&info);if(e!=ESP_OK){free(x);return e;}x->pixel_count=(size_t)info.width*info.height;x->pixels=malloc(info.decoded_bytes_per_frame);if(!x->pixels||vk_vka1_decode_frame(info.container,info.container_bytes,0,x->pixels,x->pixel_count)!=VK_VKA1_OK){release_asset(r,&info);free(x->pixels);free(x);return ESP_ERR_INVALID_RESPONSE;}release_asset(r,&info);}uint32_t token=0;esp_err_t e=vk_display_begin_flush_token(r->display,0,0,1,1,2,&token);if(e==ESP_OK){r->flushes++;e=vk_display_complete_flush_token(r->display,token,r->fail_flush?ESP_FAIL:ESP_OK);}if(e!=ESP_OK){free(x->pixels);free(x);return e;}*root=x;return ESP_OK;}
static esp_err_t swap_root(void*c,void*root,void**old){renderer_t*r=c;*old=r->active;r->active=root;r->swaps++;return ESP_OK;}static void destroy_root(void*c,void*root){renderer_t*r=c;if(root){render_root_t*x=root;free(x->pixels);free(x);r->destroys++;}}

static esp_err_t install_t(void*c){(void)c;return ESP_OK;}static esp_err_t uninstall_t(void*c){(void)c;return ESP_OK;}static int read_t(void*c,uint8_t*b,size_t cap,uint32_t timeout){(void)timeout;transport_t*t=c;size_t n=t->input_count-t->input_offset;if(n>cap)n=cap;memcpy(b,t->input+t->input_offset,n);t->input_offset+=n;return(int)n;}static int write_t(void*c,const uint8_t*b,size_t n,uint32_t timeout){(void)timeout;transport_t*t=c;if(t->output_count+n>sizeof(t->output))return-1;memcpy(t->output+t->output_count,b,n);t->output_count+=n;return(int)n;}static uint64_t now_t(void*c){return ((transport_t*)c)->fs->now_ms;}static void lock_t(void*c){(void)c;}static void unlock_t(void*c){(void)c;}
static void queue_frame(transport_t*t,uint8_t type,const uint8_t*b,size_t n){assert(n<=4092&&t->input_count+n+4<=sizeof(t->input));t->input[t->input_count++]=1;t->input[t->input_count++]=type;t->input[t->input_count++]=(uint8_t)n;t->input[t->input_count++]=(uint8_t)(n>>8);memcpy(t->input+t->input_count,b,n);t->input_count+=n;}
static void queue_json(transport_t*t,const char*j){queue_frame(t,VK_USB_FRAME_TYPE_JSON,(const uint8_t*)j,strlen(j));}
static void drain(vk_usb_service_t*s,transport_t*t){size_t guard=0;while(t->input_offset<t->input_count){assert(vk_usb_service_poll(s)==ESP_OK);assert(++guard<10000);}t->input_count=t->input_offset=0;}
static uint8_t*load_file(const char*path,size_t*size){FILE*f=fopen(path,"rb");assert(f);assert(fseek(f,0,SEEK_END)==0);long n=ftell(f);assert(n>0&&n<=4096);rewind(f);uint8_t*b=malloc((size_t)n);assert(b&&fread(b,1,(size_t)n,f)==(size_t)n);fclose(f);*size=(size_t)n;return b;}

int main(int argc,char**argv){assert(argc==2);size_t asset_bytes=0;uint8_t*asset=load_file(argv[1],&asset_bytes);vk_vka1_limits_t asset_limits={64,10,60000,4096,243104};vk_vka1_info_t asset_info;assert(vk_vka1_validate(asset,asset_bytes,&asset_limits,&asset_info)==VK_VKA1_OK);uint8_t digest[32];memcpy(digest,asset_info.sha256,sizeof(digest));char hash[65];hex_sha(digest,hash);
 fs_t fs={0};vk_asset_store_config_t sc={.fs=&fs_ops,.fs_context=&fs,.validate_vka1=validate_asset,.vka1_context=&fs,.validate_revision=validate_revision,.partition_offset=0xa20000,.partition_size=0x5e0000,.reserve_bytes=1,.max_asset_bytes=4096,.max_assets=64};vk_asset_store_t store;assert(vk_asset_store_init(&store,&sc)==ESP_OK);assert(vk_asset_store_mount(&store)==ESP_OK);
 vk_asset_transfer_service_t transfer;vk_asset_transfer_config_t tc={.store=&store,.now_ms=clock_ms,.clock_context=&fs,.chunk_bytes=32,.max_frames=64,.min_frame_ms=10,.max_frame_ms=60000,.max_active_decoded_bytes=243104,.decoder_scratch_bytes=4096,.production_available=true};assert(vk_asset_transfer_init(&transfer,&tc)==ESP_OK);
 vk_display_t display;assert(vk_display_start(&display,vk_display_product_profile(),true,true)==ESP_OK);vk_display_dependencies_t deps={true,true,true,true};assert(vk_display_set_dependencies(&display,&deps)==ESP_OK);
 renderer_t renderer={.fs=&fs,.display=&display};vk_screen_config_t cfg={.capability={.state=VK_USB_CAPABILITY_AVAILABLE,.modes=VK_USB_SCREEN_MODE_IMAGE|VK_USB_SCREEN_MODE_PET,.max_commit_bytes=4092,.max_layout_bytes=3072,.max_assets=64,.max_objects=32,.max_depth=4,.max_widgets=16,.max_fonts=1,.max_pet_states=6,.max_string_bytes=256,.max_json_tokens=512,.max_widget_value_bytes=256,.font_count=1},.assets={resolve,release_asset,&renderer},.renderer={renderer_lock,renderer_unlock,create_root,NULL,NULL,NULL,swap_root,destroy_root,&renderer},.root_budget_bytes=243104,.decoder_scratch_bytes=4096,.production_profile_admitted=true};snprintf(cfg.capability.fonts[0].id,sizeof(cfg.capability.fonts[0].id),"vk-sans");cfg.capability.fonts[0].version=1;snprintf(cfg.capability.fonts[0].metrics_sha256,sizeof(cfg.capability.fonts[0].metrics_sha256),"%s",VK_SCREEN_FONT_METRICS_SHA256);vk_screen_t screen;assert(vk_screen_init(&screen,&cfg)==ESP_OK);
 vk_screen_service_t screen_service;vk_screen_service_readiness_t ready={true,true,true,true,true,true,true};assert(vk_screen_service_init(&screen_service,&store,&transfer,&screen,&display,&ready)==ESP_OK);
 transport_t transport={.fs=&fs};vk_usb_transport_ops_t ops={install_t,uninstall_t,read_t,write_t,now_t,lock_t,unlock_t,&transport};vk_usb_identity_t identity={"vibe_keyboard","test","VS-RAM"};vk_usb_service_policy_t policy={false};vk_usb_service_t*usb=calloc(1,vk_usb_service_size());assert(usb&&vk_usb_service_init(usb,&ops,&identity,&policy)==ESP_OK);vk_usb_capability_provider_registration_t caps;vk_usb_asset_handler_registration_t assets;vk_usb_screen_handler_registration_t screens;vk_usb_widget_handler_registration_t widgets;vk_screen_service_registrations(&screen_service,&caps,&assets,&screens,&widgets);assert(vk_usb_service_register_capability_provider(usb,&caps)==ESP_OK);assert(vk_usb_service_register_asset_handler(usb,&assets)==ESP_OK);assert(vk_usb_service_register_screen_handler(usb,&screens)==ESP_OK);assert(vk_usb_service_register_widget_handler(usb,&widgets)==ESP_OK);assert(vk_usb_service_start(usb)==ESP_OK);
 queue_json(&transport,"{\"event\":\"transport\",\"kind\":\"usb\"}");drain(usb,&transport);queue_json(&transport,"{\"event\":\"get_device_info\"}");drain(usb,&transport);uint32_t epoch=vk_usb_service_epoch(usb);assert(epoch!=0);
 char json[1200];snprintf(json,sizeof(json),"{\"event\":\"vk_asset_begin\",\"transfer_id\":7,\"sha256\":\"%s\",\"total_bytes\":%u,\"kind\":\"image\"}",hash,(unsigned)asset_bytes);queue_json(&transport,json);drain(usb,&transport);vk_usb_asset_command_t tuple;uint32_t next=0;assert(vk_asset_transfer_get_state(&transfer,7,epoch,1,&tuple,&next)==ESP_OK&&next==0);
 for(size_t off=0;off<asset_bytes;){size_t n=asset_bytes-off;if(n>32)n=32;uint8_t body[40];body[0]=7;body[1]=body[2]=body[3]=0;body[4]=(uint8_t)off;body[5]=(uint8_t)(off>>8);body[6]=(uint8_t)(off>>16);body[7]=(uint8_t)(off>>24);memcpy(body+8,asset+off,n);queue_frame(&transport,VK_USB_FRAME_TYPE_ASSET_CHUNK,body,n+8);drain(usb,&transport);off+=n;assert(vk_asset_transfer_get_state(&transfer,7,epoch,1,&tuple,&next)==ESP_OK&&next==off);}
 snprintf(json,sizeof(json),"{\"event\":\"vk_asset_end\",\"transfer_id\":7,\"sha256\":\"%s\",\"total_bytes\":%u,\"kind\":\"image\"}",hash,(unsigned)asset_bytes);queue_json(&transport,json);drain(usb,&transport);assert(vk_asset_transfer_get_state(&transfer,7,epoch,1,&tuple,&next)==ESP_ERR_NOT_FOUND);
 snprintf(json,sizeof(json),"{\"assets\":{\"assets\":[{\"bytes\":%u,\"kind\":\"image\",\"sha256\":\"%s\"}]},\"event\":\"vk_screen_commit\",\"expected_revision\":0,\"revision\":1,\"screen\":{\"configured_mode\":\"image\",\"image\":{\"background_rgb888\":0,\"fit\":\"contain\",\"sha256\":\"%s\"},\"layout\":null,\"pet\":null}}",(unsigned)asset_bytes,hash,hash);queue_json(&transport,json);drain(usb,&transport);assert(screen.current.revision==1&&renderer.swaps==1&&renderer.flushes==1);
 /* Candidate and flush failures preserve the durable/current root. */renderer.fail_create=true;char failed[1200];snprintf(failed,sizeof(failed),"{\"assets\":{\"assets\":[{\"bytes\":%u,\"kind\":\"image\",\"sha256\":\"%s\"}]},\"event\":\"vk_screen_commit\",\"expected_revision\":1,\"revision\":2,\"screen\":{\"configured_mode\":\"image\",\"image\":{\"background_rgb888\":0,\"fit\":\"contain\",\"sha256\":\"%s\"},\"layout\":null,\"pet\":null}}",(unsigned)asset_bytes,hash,hash);queue_json(&transport,failed);drain(usb,&transport);assert(screen.current.revision==1&&store.selected_revision==1&&renderer.swaps==1);renderer.fail_create=false;
 assert(vk_usb_service_stop(usb)==ESP_OK);free(usb);assert(vk_screen_stop(&screen)==ESP_OK);
 /* Process-style reconstruction from the same durable RAM filesystem. */vk_asset_store_t reboot;assert(vk_asset_store_init(&reboot,&sc)==ESP_OK);assert(vk_asset_store_mount(&reboot)==ESP_OK);vk_asset_recovery_t recovery;assert(vk_asset_store_recover(&reboot,&recovery)==ESP_OK&&recovery.current_revision==1);renderer_t restored_renderer={.fs=&fs,.display=&display};cfg.assets.context=&restored_renderer;cfg.renderer.context=&restored_renderer;vk_screen_t restored;assert(vk_screen_init(&restored,&cfg)==ESP_OK);vk_screen_service_t restored_service={.store=&reboot,.transfer=&transfer,.screen=&restored,.display=&display};vk_usb_json_document_t document;uint8_t envelope[VK_USB_MAX_JSON_BYTES];assert(vk_screen_service_restore(&restored_service,&recovery,&document,envelope,sizeof(envelope))==ESP_OK);assert(restored.current.revision==1&&restored_renderer.swaps==1&&restored_renderer.flushes==1);assert(vk_screen_stop(&restored)==ESP_OK);assert(vk_display_stop(&display)==ESP_OK);free(asset);puts("USB asset screen VKA1 recovery display chain passed");return 0;}
